/* tslint:disable */
/* eslint-disable */
/**
 * PDI Session Service
 * Microservice pour la gestion des séances PDI selon le cahier des charges ENGY PARTNERS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

