/* tslint:disable */
/* eslint-disable */
/**
 * Event Service
 * FastAPI microservice for event management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Schema for cancellation response
 * @export
 * @interface CancellationResponse
 */
export interface CancellationResponse {
    /**
     * Cancellation status message
     * @type {string}
     * @memberof CancellationResponse
     */
    'message': string;
    /**
     * Registration ID
     * @type {string}
     * @memberof CancellationResponse
     */
    'registration_id': string;
    /**
     * Event ID
     * @type {string}
     * @memberof CancellationResponse
     */
    'event_id': string;
}
/**
 * Schema for creating a new event
 * @export
 * @interface EventCreate
 */
export interface EventCreate {
    /**
     * Event title
     * @type {string}
     * @memberof EventCreate
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EventCreate
     */
    'description'?: string | null;
    /**
     * Event category
     * @type {string}
     * @memberof EventCreate
     */
    'category': EventCreateCategoryEnum;
    /**
     * Event start time
     * @type {string}
     * @memberof EventCreate
     */
    'start_time': string;
    /**
     * Event end time
     * @type {string}
     * @memberof EventCreate
     */
    'end_time': string;
    /**
     * 
     * @type {string}
     * @memberof EventCreate
     */
    'location'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventCreate
     */
    'capacity'?: number | null;
    /**
     * ID de l\'établissement
     * @type {string}
     * @memberof EventCreate
     */
    'etablissement_id': string;
}

export const EventCreateCategoryEnum = {
    Sortie: 'Sortie',
    Crmonie: 'Cérémonie',
    Club: 'Club',
    Autre: 'Autre'
} as const;

export type EventCreateCategoryEnum = typeof EventCreateCategoryEnum[keyof typeof EventCreateCategoryEnum];

/**
 * Schema for event response
 * @export
 * @interface EventOut
 */
export interface EventOut {
    /**
     * Event ID
     * @type {string}
     * @memberof EventOut
     */
    'id': string;
    /**
     * Event title
     * @type {string}
     * @memberof EventOut
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EventOut
     */
    'description'?: string | null;
    /**
     * Event category
     * @type {string}
     * @memberof EventOut
     */
    'category': EventOutCategoryEnum;
    /**
     * Event start time
     * @type {string}
     * @memberof EventOut
     */
    'start_time': string;
    /**
     * Event end time
     * @type {string}
     * @memberof EventOut
     */
    'end_time': string;
    /**
     * 
     * @type {string}
     * @memberof EventOut
     */
    'location'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventOut
     */
    'capacity'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EventOut
     */
    'etablissement_id'?: string | null;
    /**
     * Event status
     * @type {string}
     * @memberof EventOut
     */
    'status': EventOutStatusEnum;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof EventOut
     */
    'created_at': string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof EventOut
     */
    'updated_at': string;
}

export const EventOutCategoryEnum = {
    Sortie: 'Sortie',
    Crmonie: 'Cérémonie',
    Club: 'Club',
    Autre: 'Autre'
} as const;

export type EventOutCategoryEnum = typeof EventOutCategoryEnum[keyof typeof EventOutCategoryEnum];
export const EventOutStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type EventOutStatusEnum = typeof EventOutStatusEnum[keyof typeof EventOutStatusEnum];

/**
 * Schema for updating an event (all fields optional)
 * @export
 * @interface EventUpdate
 */
export interface EventUpdate {
    /**
     * 
     * @type {string}
     * @memberof EventUpdate
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdate
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdate
     */
    'category'?: EventUpdateCategoryEnum | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdate
     */
    'start_time'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdate
     */
    'end_time'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdate
     */
    'location'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventUpdate
     */
    'capacity'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdate
     */
    'status'?: EventUpdateStatusEnum | null;
}

export const EventUpdateCategoryEnum = {
    Sortie: 'Sortie',
    Crmonie: 'Cérémonie',
    Club: 'Club',
    Autre: 'Autre'
} as const;

export type EventUpdateCategoryEnum = typeof EventUpdateCategoryEnum[keyof typeof EventUpdateCategoryEnum];
export const EventUpdateStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type EventUpdateStatusEnum = typeof EventUpdateStatusEnum[keyof typeof EventUpdateStatusEnum];

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * Schema for registration request
 * @export
 * @interface RegistrationRequest
 */
export interface RegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    'participant_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    'participant_role'?: string | null;
}
/**
 * Schema for registration response
 * @export
 * @interface RegistrationResponse
 */
export interface RegistrationResponse {
    /**
     * Registration status message
     * @type {string}
     * @memberof RegistrationResponse
     */
    'message': string;
    /**
     * Registration ID
     * @type {string}
     * @memberof RegistrationResponse
     */
    'registration_id': string;
    /**
     * Registration status (CONFIRMED or WAITING)
     * @type {string}
     * @memberof RegistrationResponse
     */
    'status': string;
    /**
     * Event ID
     * @type {string}
     * @memberof RegistrationResponse
     */
    'event_id': string;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Health check endpoint
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Root endpoint
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Health check endpoint
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthCheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Root endpoint
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.rootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Health check endpoint
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Root endpoint
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Health check endpoint
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheckHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Root endpoint
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EventsApi - axios parameter creator
 * @export
 */
export const EventsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Annuler une inscription à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
         * @summary Cancel Registration
         * @param {string} eventId 
         * @param {string} registrationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete: async (eventId: string, registrationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete', 'eventId', eventId)
            // verify required parameter 'registrationId' is not null or undefined
            assertParamExists('cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete', 'registrationId', registrationId)
            const localVarPath = `/api/v1/events/{event_id}/register/{registration_id}`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)))
                .replace(`{${"registration_id"}}`, encodeURIComponent(String(registrationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Créer un nouvel événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Create Event
         * @param {EventCreate} eventCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEventApiV1EventsPost: async (eventCreate: EventCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventCreate' is not null or undefined
            assertParamExists('createEventApiV1EventsPost', 'eventCreate', eventCreate)
            const localVarPath = `/api/v1/events/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(eventCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Supprimer un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Delete Event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEventApiV1EventsEventIdDelete: async (eventId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('deleteEventApiV1EventsEventIdDelete', 'eventId', eventId)
            const localVarPath = `/api/v1/events/{event_id}`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Télécharger la feuille de présence d\'un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Export Attendance
         * @param {string} eventId 
         * @param {string} [format] Format d\&#39;export (pdf ou csv)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportAttendanceApiV1EventsEventIdExportGet: async (eventId: string, format?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('exportAttendanceApiV1EventsEventIdExportGet', 'eventId', eventId)
            const localVarPath = `/api/v1/events/{event_id}/export`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupérer un événement spécifique par ID avec validation tenant.
         * @summary Get Event By Id
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEventByIdApiV1EventsEventIdGet: async (eventId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('getEventByIdApiV1EventsEventIdGet', 'eventId', eventId)
            const localVarPath = `/api/v1/events/{event_id}`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère tous les participants à un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Get Participants
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getParticipantsApiV1EventsEventIdParticipantsGet: async (eventId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('getParticipantsApiV1EventsEventIdParticipantsGet', 'eventId', eventId)
            const localVarPath = `/api/v1/events/{event_id}/participants`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lister tous les événements avec pagination et filtrage selon le contexte tenant.
         * @summary List Events
         * @param {number} [page] Page number (minimum 1)
         * @param {number} [size] Items per page (1-100)
         * @param {string | null} [category] Filter by event category
         * @param {string | null} [startDate] Filter events starting after this date
         * @param {string | null} [endDate] Filter events ending before this date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEventsApiV1EventsGet: async (page?: number, size?: number, category?: string | null, startDate?: string | null, endDate?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/events/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Publier un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Publish Event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publishEventApiV1EventsEventIdPublishPost: async (eventId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('publishEventApiV1EventsEventIdPublishPost', 'eventId', eventId)
            const localVarPath = `/api/v1/events/{event_id}/publish`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * S\'inscrire à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
         * @summary Register Participant
         * @param {string} eventId 
         * @param {RegistrationRequest} registrationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerParticipantApiV1EventsEventIdRegisterPost: async (eventId: string, registrationRequest: RegistrationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('registerParticipantApiV1EventsEventIdRegisterPost', 'eventId', eventId)
            // verify required parameter 'registrationRequest' is not null or undefined
            assertParamExists('registerParticipantApiV1EventsEventIdRegisterPost', 'registrationRequest', registrationRequest)
            const localVarPath = `/api/v1/events/{event_id}/register`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registrationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modifier un événement existant (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Update Event
         * @param {string} eventId 
         * @param {EventUpdate} eventUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEventApiV1EventsEventIdPatch: async (eventId: string, eventUpdate: EventUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('updateEventApiV1EventsEventIdPatch', 'eventId', eventId)
            // verify required parameter 'eventUpdate' is not null or undefined
            assertParamExists('updateEventApiV1EventsEventIdPatch', 'eventUpdate', eventUpdate)
            const localVarPath = `/api/v1/events/{event_id}`
                .replace(`{${"event_id"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(eventUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventsApi - functional programming interface
 * @export
 */
export const EventsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventsApiAxiosParamCreator(configuration)
    return {
        /**
         * Annuler une inscription à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
         * @summary Cancel Registration
         * @param {string} eventId 
         * @param {string} registrationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete(eventId: string, registrationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancellationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete(eventId, registrationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Créer un nouvel événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Create Event
         * @param {EventCreate} eventCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createEventApiV1EventsPost(eventCreate: EventCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createEventApiV1EventsPost(eventCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.createEventApiV1EventsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Supprimer un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Delete Event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEventApiV1EventsEventIdDelete(eventId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteEventApiV1EventsEventIdDelete(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.deleteEventApiV1EventsEventIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Télécharger la feuille de présence d\'un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Export Attendance
         * @param {string} eventId 
         * @param {string} [format] Format d\&#39;export (pdf ou csv)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportAttendanceApiV1EventsEventIdExportGet(eventId: string, format?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportAttendanceApiV1EventsEventIdExportGet(eventId, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.exportAttendanceApiV1EventsEventIdExportGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupérer un événement spécifique par ID avec validation tenant.
         * @summary Get Event By Id
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEventByIdApiV1EventsEventIdGet(eventId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEventByIdApiV1EventsEventIdGet(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.getEventByIdApiV1EventsEventIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère tous les participants à un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Get Participants
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getParticipantsApiV1EventsEventIdParticipantsGet(eventId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getParticipantsApiV1EventsEventIdParticipantsGet(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.getParticipantsApiV1EventsEventIdParticipantsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lister tous les événements avec pagination et filtrage selon le contexte tenant.
         * @summary List Events
         * @param {number} [page] Page number (minimum 1)
         * @param {number} [size] Items per page (1-100)
         * @param {string | null} [category] Filter by event category
         * @param {string | null} [startDate] Filter events starting after this date
         * @param {string | null} [endDate] Filter events ending before this date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEventsApiV1EventsGet(page?: number, size?: number, category?: string | null, startDate?: string | null, endDate?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEventsApiV1EventsGet(page, size, category, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.listEventsApiV1EventsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Publier un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Publish Event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publishEventApiV1EventsEventIdPublishPost(eventId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publishEventApiV1EventsEventIdPublishPost(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.publishEventApiV1EventsEventIdPublishPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * S\'inscrire à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
         * @summary Register Participant
         * @param {string} eventId 
         * @param {RegistrationRequest} registrationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerParticipantApiV1EventsEventIdRegisterPost(eventId: string, registrationRequest: RegistrationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerParticipantApiV1EventsEventIdRegisterPost(eventId, registrationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.registerParticipantApiV1EventsEventIdRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modifier un événement existant (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Update Event
         * @param {string} eventId 
         * @param {EventUpdate} eventUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEventApiV1EventsEventIdPatch(eventId: string, eventUpdate: EventUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEventApiV1EventsEventIdPatch(eventId, eventUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.updateEventApiV1EventsEventIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventsApi - factory interface
 * @export
 */
export const EventsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventsApiFp(configuration)
    return {
        /**
         * Annuler une inscription à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
         * @summary Cancel Registration
         * @param {string} eventId 
         * @param {string} registrationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete(eventId: string, registrationId: string, options?: RawAxiosRequestConfig): AxiosPromise<CancellationResponse> {
            return localVarFp.cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete(eventId, registrationId, options).then((request) => request(axios, basePath));
        },
        /**
         * Créer un nouvel événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Create Event
         * @param {EventCreate} eventCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEventApiV1EventsPost(eventCreate: EventCreate, options?: RawAxiosRequestConfig): AxiosPromise<EventOut> {
            return localVarFp.createEventApiV1EventsPost(eventCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Supprimer un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Delete Event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEventApiV1EventsEventIdDelete(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteEventApiV1EventsEventIdDelete(eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * Télécharger la feuille de présence d\'un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Export Attendance
         * @param {string} eventId 
         * @param {string} [format] Format d\&#39;export (pdf ou csv)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportAttendanceApiV1EventsEventIdExportGet(eventId: string, format?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.exportAttendanceApiV1EventsEventIdExportGet(eventId, format, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupérer un événement spécifique par ID avec validation tenant.
         * @summary Get Event By Id
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEventByIdApiV1EventsEventIdGet(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<EventOut> {
            return localVarFp.getEventByIdApiV1EventsEventIdGet(eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère tous les participants à un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Get Participants
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getParticipantsApiV1EventsEventIdParticipantsGet(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getParticipantsApiV1EventsEventIdParticipantsGet(eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * Lister tous les événements avec pagination et filtrage selon le contexte tenant.
         * @summary List Events
         * @param {number} [page] Page number (minimum 1)
         * @param {number} [size] Items per page (1-100)
         * @param {string | null} [category] Filter by event category
         * @param {string | null} [startDate] Filter events starting after this date
         * @param {string | null} [endDate] Filter events ending before this date
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEventsApiV1EventsGet(page?: number, size?: number, category?: string | null, startDate?: string | null, endDate?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.listEventsApiV1EventsGet(page, size, category, startDate, endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Publier un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Publish Event
         * @param {string} eventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publishEventApiV1EventsEventIdPublishPost(eventId: string, options?: RawAxiosRequestConfig): AxiosPromise<EventOut> {
            return localVarFp.publishEventApiV1EventsEventIdPublishPost(eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * S\'inscrire à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
         * @summary Register Participant
         * @param {string} eventId 
         * @param {RegistrationRequest} registrationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerParticipantApiV1EventsEventIdRegisterPost(eventId: string, registrationRequest: RegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegistrationResponse> {
            return localVarFp.registerParticipantApiV1EventsEventIdRegisterPost(eventId, registrationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Modifier un événement existant (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
         * @summary Update Event
         * @param {string} eventId 
         * @param {EventUpdate} eventUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEventApiV1EventsEventIdPatch(eventId: string, eventUpdate: EventUpdate, options?: RawAxiosRequestConfig): AxiosPromise<EventOut> {
            return localVarFp.updateEventApiV1EventsEventIdPatch(eventId, eventUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventsApi - object-oriented interface
 * @export
 * @class EventsApi
 * @extends {BaseAPI}
 */
export class EventsApi extends BaseAPI {
    /**
     * Annuler une inscription à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
     * @summary Cancel Registration
     * @param {string} eventId 
     * @param {string} registrationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete(eventId: string, registrationId: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).cancelRegistrationApiV1EventsEventIdRegisterRegistrationIdDelete(eventId, registrationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Créer un nouvel événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
     * @summary Create Event
     * @param {EventCreate} eventCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public createEventApiV1EventsPost(eventCreate: EventCreate, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).createEventApiV1EventsPost(eventCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Supprimer un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
     * @summary Delete Event
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public deleteEventApiV1EventsEventIdDelete(eventId: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).deleteEventApiV1EventsEventIdDelete(eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Télécharger la feuille de présence d\'un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
     * @summary Export Attendance
     * @param {string} eventId 
     * @param {string} [format] Format d\&#39;export (pdf ou csv)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public exportAttendanceApiV1EventsEventIdExportGet(eventId: string, format?: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).exportAttendanceApiV1EventsEventIdExportGet(eventId, format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupérer un événement spécifique par ID avec validation tenant.
     * @summary Get Event By Id
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public getEventByIdApiV1EventsEventIdGet(eventId: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).getEventByIdApiV1EventsEventIdGet(eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère tous les participants à un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
     * @summary Get Participants
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public getParticipantsApiV1EventsEventIdParticipantsGet(eventId: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).getParticipantsApiV1EventsEventIdParticipantsGet(eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lister tous les événements avec pagination et filtrage selon le contexte tenant.
     * @summary List Events
     * @param {number} [page] Page number (minimum 1)
     * @param {number} [size] Items per page (1-100)
     * @param {string | null} [category] Filter by event category
     * @param {string | null} [startDate] Filter events starting after this date
     * @param {string | null} [endDate] Filter events ending before this date
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public listEventsApiV1EventsGet(page?: number, size?: number, category?: string | null, startDate?: string | null, endDate?: string | null, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).listEventsApiV1EventsGet(page, size, category, startDate, endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Publier un événement (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
     * @summary Publish Event
     * @param {string} eventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public publishEventApiV1EventsEventIdPublishPost(eventId: string, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).publishEventApiV1EventsEventIdPublishPost(eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * S\'inscrire à un événement (ROLE_ELEVE, ROLE_PARENT, ROLE_ADMINSTAFF)
     * @summary Register Participant
     * @param {string} eventId 
     * @param {RegistrationRequest} registrationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public registerParticipantApiV1EventsEventIdRegisterPost(eventId: string, registrationRequest: RegistrationRequest, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).registerParticipantApiV1EventsEventIdRegisterPost(eventId, registrationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modifier un événement existant (ROLE_ADMINSTAFF, ROLE_ADMIN uniquement)
     * @summary Update Event
     * @param {string} eventId 
     * @param {EventUpdate} eventUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public updateEventApiV1EventsEventIdPatch(eventId: string, eventUpdate: EventUpdate, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).updateEventApiV1EventsEventIdPatch(eventId, eventUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}



