/* tslint:disable */
/* eslint-disable */
/**
 * Timetable Service
 * API REST conforme au cahier des charges avec authentification par en-têtes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

