/* tslint:disable */
/* eslint-disable */
/**
 * EdConnect - message-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ConversationCreate
 */
export interface ConversationCreate {
    /**
     * 
     * @type {string}
     * @memberof ConversationCreate
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationCreate
     */
    'title'?: string | null;
    /**
     * 
     * @type {Array<ConversationMemberIn>}
     * @memberof ConversationCreate
     */
    'members': Array<ConversationMemberIn>;
}
/**
 * 
 * @export
 * @interface ConversationMemberIn
 */
export interface ConversationMemberIn {
    /**
     * 
     * @type {string}
     * @memberof ConversationMemberIn
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMemberIn
     */
    'role'?: string | null;
}
/**
 * 
 * @export
 * @interface ConversationOut
 */
export interface ConversationOut {
    /**
     * 
     * @type {string}
     * @memberof ConversationOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationOut
     */
    'tenant_id': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationOut
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationOut
     */
    'title'?: string | null;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface MessageCreate
 */
export interface MessageCreate {
    /**
     * 
     * @type {string}
     * @memberof MessageCreate
     */
    'type': MessageCreateTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof MessageCreate
     */
    'content': object;
}

export const MessageCreateTypeEnum = {
    Text: 'TEXT',
    Image: 'IMAGE',
    File: 'FILE',
    System: 'SYSTEM'
} as const;

export type MessageCreateTypeEnum = typeof MessageCreateTypeEnum[keyof typeof MessageCreateTypeEnum];

/**
 * 
 * @export
 * @interface MessageDelete
 */
export interface MessageDelete {
    /**
     * 
     * @type {string}
     * @memberof MessageDelete
     */
    'reason'?: string | null;
}
/**
 * 
 * @export
 * @interface MessageEdit
 */
export interface MessageEdit {
    /**
     * 
     * @type {object}
     * @memberof MessageEdit
     */
    'content': object;
}
/**
 * 
 * @export
 * @interface MessageOut
 */
export interface MessageOut {
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    'conversation_id': string;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    'sender_id': string;
    /**
     * 
     * @type {string}
     * @memberof MessageOut
     */
    'type': string;
    /**
     * 
     * @type {object}
     * @memberof MessageOut
     */
    'content': object;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * ConversationsApi - axios parameter creator
 * @export
 */
export const ConversationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Conversation
         * @param {ConversationCreate} conversationCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createConversationConversationsPost: async (conversationCreate: ConversationCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationCreate' is not null or undefined
            assertParamExists('createConversationConversationsPost', 'conversationCreate', conversationCreate)
            const localVarPath = `/conversations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(conversationCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Conversations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listConversationsConversationsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/conversations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConversationsApi - functional programming interface
 * @export
 */
export const ConversationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConversationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Conversation
         * @param {ConversationCreate} conversationCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createConversationConversationsPost(conversationCreate: ConversationCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConversationOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createConversationConversationsPost(conversationCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConversationsApi.createConversationConversationsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Conversations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listConversationsConversationsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ConversationOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listConversationsConversationsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConversationsApi.listConversationsConversationsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ConversationsApi - factory interface
 * @export
 */
export const ConversationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConversationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Conversation
         * @param {ConversationCreate} conversationCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createConversationConversationsPost(conversationCreate: ConversationCreate, options?: RawAxiosRequestConfig): AxiosPromise<ConversationOut> {
            return localVarFp.createConversationConversationsPost(conversationCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Conversations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listConversationsConversationsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<ConversationOut>> {
            return localVarFp.listConversationsConversationsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ConversationsApi - object-oriented interface
 * @export
 * @class ConversationsApi
 * @extends {BaseAPI}
 */
export class ConversationsApi extends BaseAPI {
    /**
     * 
     * @summary Create Conversation
     * @param {ConversationCreate} conversationCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApi
     */
    public createConversationConversationsPost(conversationCreate: ConversationCreate, options?: RawAxiosRequestConfig) {
        return ConversationsApiFp(this.configuration).createConversationConversationsPost(conversationCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Conversations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApi
     */
    public listConversationsConversationsGet(options?: RawAxiosRequestConfig) {
        return ConversationsApiFp(this.configuration).listConversationsConversationsGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Healthz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthzHealthzGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/healthz`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Readyz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readyzReadyzGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/readyz`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Healthz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthzHealthzGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthzHealthzGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthzHealthzGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.meMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Readyz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readyzReadyzGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readyzReadyzGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.readyzReadyzGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Healthz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthzHealthzGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthzHealthzGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meMeGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.meMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Readyz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readyzReadyzGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.readyzReadyzGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Healthz
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthzHealthzGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthzHealthzGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public meMeGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).meMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Readyz
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readyzReadyzGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readyzReadyzGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MessagesApi - axios parameter creator
 * @export
 */
export const MessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Message
         * @param {string} messageId 
         * @param {MessageDelete} [messageDelete] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessageConversationsMessagesMessageIdDeletePost: async (messageId: string, messageDelete?: MessageDelete, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messageId' is not null or undefined
            assertParamExists('deleteMessageConversationsMessagesMessageIdDeletePost', 'messageId', messageId)
            const localVarPath = `/conversations/messages/{message_id}/delete`
                .replace(`{${"message_id"}}`, encodeURIComponent(String(messageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(messageDelete, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edit Message
         * @param {string} messageId 
         * @param {MessageEdit} messageEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editMessageConversationsMessagesMessageIdEditPost: async (messageId: string, messageEdit: MessageEdit, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messageId' is not null or undefined
            assertParamExists('editMessageConversationsMessagesMessageIdEditPost', 'messageId', messageId)
            // verify required parameter 'messageEdit' is not null or undefined
            assertParamExists('editMessageConversationsMessagesMessageIdEditPost', 'messageEdit', messageEdit)
            const localVarPath = `/conversations/messages/{message_id}/edit`
                .replace(`{${"message_id"}}`, encodeURIComponent(String(messageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(messageEdit, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Messages
         * @param {string} conversationId 
         * @param {number} [limit] 
         * @param {string | null} [after] 
         * @param {string | null} [before] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMessagesConversationsConversationIdMessagesGet: async (conversationId: string, limit?: number, after?: string | null, before?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationId' is not null or undefined
            assertParamExists('listMessagesConversationsConversationIdMessagesGet', 'conversationId', conversationId)
            const localVarPath = `/conversations/{conversation_id}/messages`
                .replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (after !== undefined) {
                localVarQueryParameter['after'] = after;
            }

            if (before !== undefined) {
                localVarQueryParameter['before'] = before;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Send Message
         * @param {string} conversationId 
         * @param {MessageCreate} messageCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessageConversationsConversationIdMessagesPost: async (conversationId: string, messageCreate: MessageCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationId' is not null or undefined
            assertParamExists('sendMessageConversationsConversationIdMessagesPost', 'conversationId', conversationId)
            // verify required parameter 'messageCreate' is not null or undefined
            assertParamExists('sendMessageConversationsConversationIdMessagesPost', 'messageCreate', messageCreate)
            const localVarPath = `/conversations/{conversation_id}/messages`
                .replace(`{${"conversation_id"}}`, encodeURIComponent(String(conversationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(messageCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessagesApi - functional programming interface
 * @export
 */
export const MessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete Message
         * @param {string} messageId 
         * @param {MessageDelete} [messageDelete] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMessageConversationsMessagesMessageIdDeletePost(messageId: string, messageDelete?: MessageDelete, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMessageConversationsMessagesMessageIdDeletePost(messageId, messageDelete, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.deleteMessageConversationsMessagesMessageIdDeletePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Edit Message
         * @param {string} messageId 
         * @param {MessageEdit} messageEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editMessageConversationsMessagesMessageIdEditPost(messageId: string, messageEdit: MessageEdit, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editMessageConversationsMessagesMessageIdEditPost(messageId, messageEdit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.editMessageConversationsMessagesMessageIdEditPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Messages
         * @param {string} conversationId 
         * @param {number} [limit] 
         * @param {string | null} [after] 
         * @param {string | null} [before] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMessagesConversationsConversationIdMessagesGet(conversationId: string, limit?: number, after?: string | null, before?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MessageOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMessagesConversationsConversationIdMessagesGet(conversationId, limit, after, before, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.listMessagesConversationsConversationIdMessagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Send Message
         * @param {string} conversationId 
         * @param {MessageCreate} messageCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendMessageConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendMessageConversationsConversationIdMessagesPost(conversationId, messageCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagesApi.sendMessageConversationsConversationIdMessagesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessagesApi - factory interface
 * @export
 */
export const MessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessagesApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete Message
         * @param {string} messageId 
         * @param {MessageDelete} [messageDelete] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessageConversationsMessagesMessageIdDeletePost(messageId: string, messageDelete?: MessageDelete, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.deleteMessageConversationsMessagesMessageIdDeletePost(messageId, messageDelete, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edit Message
         * @param {string} messageId 
         * @param {MessageEdit} messageEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editMessageConversationsMessagesMessageIdEditPost(messageId: string, messageEdit: MessageEdit, options?: RawAxiosRequestConfig): AxiosPromise<MessageOut> {
            return localVarFp.editMessageConversationsMessagesMessageIdEditPost(messageId, messageEdit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Messages
         * @param {string} conversationId 
         * @param {number} [limit] 
         * @param {string | null} [after] 
         * @param {string | null} [before] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMessagesConversationsConversationIdMessagesGet(conversationId: string, limit?: number, after?: string | null, before?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<Array<MessageOut>> {
            return localVarFp.listMessagesConversationsConversationIdMessagesGet(conversationId, limit, after, before, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Send Message
         * @param {string} conversationId 
         * @param {MessageCreate} messageCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessageConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, options?: RawAxiosRequestConfig): AxiosPromise<MessageOut> {
            return localVarFp.sendMessageConversationsConversationIdMessagesPost(conversationId, messageCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessagesApi - object-oriented interface
 * @export
 * @class MessagesApi
 * @extends {BaseAPI}
 */
export class MessagesApi extends BaseAPI {
    /**
     * 
     * @summary Delete Message
     * @param {string} messageId 
     * @param {MessageDelete} [messageDelete] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    public deleteMessageConversationsMessagesMessageIdDeletePost(messageId: string, messageDelete?: MessageDelete, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).deleteMessageConversationsMessagesMessageIdDeletePost(messageId, messageDelete, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Edit Message
     * @param {string} messageId 
     * @param {MessageEdit} messageEdit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    public editMessageConversationsMessagesMessageIdEditPost(messageId: string, messageEdit: MessageEdit, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).editMessageConversationsMessagesMessageIdEditPost(messageId, messageEdit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Messages
     * @param {string} conversationId 
     * @param {number} [limit] 
     * @param {string | null} [after] 
     * @param {string | null} [before] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    public listMessagesConversationsConversationIdMessagesGet(conversationId: string, limit?: number, after?: string | null, before?: string | null, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).listMessagesConversationsConversationIdMessagesGet(conversationId, limit, after, before, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Send Message
     * @param {string} conversationId 
     * @param {MessageCreate} messageCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    public sendMessageConversationsConversationIdMessagesPost(conversationId: string, messageCreate: MessageCreate, options?: RawAxiosRequestConfig) {
        return MessagesApiFp(this.configuration).sendMessageConversationsConversationIdMessagesPost(conversationId, messageCreate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UploadsApi - axios parameter creator
 * @export
 */
export const UploadsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Upload Key
         * @param {string | null} [filename] 
         * @param {string | null} [contentType] 
         * @param {number | null} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUploadKeyMessagesUploadPost: async (filename?: string | null, contentType?: string | null, size?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/messages/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (filename !== undefined) {
                localVarQueryParameter['filename'] = filename;
            }

            if (contentType !== undefined) {
                localVarQueryParameter['content_type'] = contentType;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get File
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFileFilesKeyGet: async (key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('getFileFilesKeyGet', 'key', key)
            const localVarPath = `/files/{key}`
                .replace(`{${"key"}}`, encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload File
         * @param {string} key 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileUploadsKeyPut: async (key: string, file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('uploadFileUploadsKeyPut', 'key', key)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadFileUploadsKeyPut', 'file', file)
            const localVarPath = `/uploads/{key}`
                .replace(`{${"key"}}`, encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UploadsApi - functional programming interface
 * @export
 */
export const UploadsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UploadsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Upload Key
         * @param {string | null} [filename] 
         * @param {string | null} [contentType] 
         * @param {number | null} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUploadKeyMessagesUploadPost(filename?: string | null, contentType?: string | null, size?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUploadKeyMessagesUploadPost(filename, contentType, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadsApi.createUploadKeyMessagesUploadPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get File
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFileFilesKeyGet(key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFileFilesKeyGet(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadsApi.getFileFilesKeyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload File
         * @param {string} key 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFileUploadsKeyPut(key: string, file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFileUploadsKeyPut(key, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadsApi.uploadFileUploadsKeyPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UploadsApi - factory interface
 * @export
 */
export const UploadsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UploadsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Upload Key
         * @param {string | null} [filename] 
         * @param {string | null} [contentType] 
         * @param {number | null} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUploadKeyMessagesUploadPost(filename?: string | null, contentType?: string | null, size?: number | null, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.createUploadKeyMessagesUploadPost(filename, contentType, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get File
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFileFilesKeyGet(key: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getFileFilesKeyGet(key, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload File
         * @param {string} key 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileUploadsKeyPut(key: string, file: File, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.uploadFileUploadsKeyPut(key, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UploadsApi - object-oriented interface
 * @export
 * @class UploadsApi
 * @extends {BaseAPI}
 */
export class UploadsApi extends BaseAPI {
    /**
     * 
     * @summary Create Upload Key
     * @param {string | null} [filename] 
     * @param {string | null} [contentType] 
     * @param {number | null} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApi
     */
    public createUploadKeyMessagesUploadPost(filename?: string | null, contentType?: string | null, size?: number | null, options?: RawAxiosRequestConfig) {
        return UploadsApiFp(this.configuration).createUploadKeyMessagesUploadPost(filename, contentType, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get File
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApi
     */
    public getFileFilesKeyGet(key: string, options?: RawAxiosRequestConfig) {
        return UploadsApiFp(this.configuration).getFileFilesKeyGet(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload File
     * @param {string} key 
     * @param {File} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApi
     */
    public uploadFileUploadsKeyPut(key: string, file: File, options?: RawAxiosRequestConfig) {
        return UploadsApiFp(this.configuration).uploadFileUploadsKeyPut(key, file, options).then((request) => request(this.axios, this.basePath));
    }
}



