/* tslint:disable */
/* eslint-disable */
/**
 * Classe Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ClasseAuditOut
 */
export interface ClasseAuditOut {
    /**
     * 
     * @type {string}
     * @memberof ClasseAuditOut
     */
    'classe_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseAuditOut
     */
    'operation': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseAuditOut
     */
    'motif': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseAuditOut
     */
    'auteur_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseAuditOut
     */
    'auteur_nom': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseAuditOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseAuditOut
     */
    'date_operation': string;
}
/**
 * 
 * @export
 * @interface ClasseCreate
 */
export interface ClasseCreate {
    /**
     * 
     * @type {string}
     * @memberof ClasseCreate
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseCreate
     */
    'nom': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseCreate
     */
    'niveau': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseCreate
     */
    'annee_scolaire': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseCreate
     */
    'etablissement_id': string;
    /**
     * 
     * @type {number}
     * @memberof ClasseCreate
     */
    'capacity'?: number;
}
/**
 * 
 * @export
 * @interface ClasseEleveCreate
 */
export interface ClasseEleveCreate {
    /**
     * 
     * @type {string}
     * @memberof ClasseEleveCreate
     */
    'classe_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEleveCreate
     */
    'eleve_id': string;
}
/**
 * 
 * @export
 * @interface ClasseEleveOut
 */
export interface ClasseEleveOut {
    /**
     * 
     * @type {string}
     * @memberof ClasseEleveOut
     */
    'classe_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEleveOut
     */
    'eleve_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEleveOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEleveOut
     */
    'date_entree': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEleveOut
     */
    'date_sortie': string | null;
}
/**
 * 
 * @export
 * @interface ClasseEnseignantCreate
 */
export interface ClasseEnseignantCreate {
    /**
     * 
     * @type {string}
     * @memberof ClasseEnseignantCreate
     */
    'classe_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEnseignantCreate
     */
    'enseignant_kc_id': string;
}
/**
 * 
 * @export
 * @interface ClasseEnseignantOut
 */
export interface ClasseEnseignantOut {
    /**
     * 
     * @type {string}
     * @memberof ClasseEnseignantOut
     */
    'classe_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEnseignantOut
     */
    'enseignant_kc_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEnseignantOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEnseignantOut
     */
    'date_affectation': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseEnseignantOut
     */
    'date_fin': string | null;
}
/**
 * 
 * @export
 * @interface ClasseHistoryOut
 */
export interface ClasseHistoryOut {
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'history_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'original_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'nom': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'niveau': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'annee_scolaire': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'etablissement_id': string;
    /**
     * 
     * @type {number}
     * @memberof ClasseHistoryOut
     */
    'capacity': number;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'archived_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'createur_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'created_by': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'updated_at': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'updated_by': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'op': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'op_reason': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'change_type': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'changed_at': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseHistoryOut
     */
    'changed_by': string | null;
}
/**
 * 
 * @export
 * @interface ClasseOut
 */
export interface ClasseOut {
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'nom': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'niveau': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'annee_scolaire': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'etablissement_id': string;
    /**
     * 
     * @type {number}
     * @memberof ClasseOut
     */
    'capacity'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'createur_id': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'created_by': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'updated_at': string;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'updated_by': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'op': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'op_reason': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseOut
     */
    'archived_at': string | null;
}
/**
 * 
 * @export
 * @interface ClasseStatistics
 */
export interface ClasseStatistics {
    /**
     * 
     * @type {number}
     * @memberof ClasseStatistics
     */
    'nombre_eleves': number;
    /**
     * 
     * @type {number}
     * @memberof ClasseStatistics
     */
    'nombre_enseignants': number;
    /**
     * 
     * @type {number}
     * @memberof ClasseStatistics
     */
    'taux_remplissage': number;
    /**
     * 
     * @type {number}
     * @memberof ClasseStatistics
     */
    'moyenne_age_eleves'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseStatistics
     */
    'dernier_evenement_classe'?: string | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ClasseStatistics
     */
    'pourcentage_filles_garcons'?: { [key: string]: number; } | null;
}
/**
 * 
 * @export
 * @interface ClasseUpdate
 */
export interface ClasseUpdate {
    /**
     * 
     * @type {string}
     * @memberof ClasseUpdate
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseUpdate
     */
    'nom': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseUpdate
     */
    'niveau': string | null;
    /**
     * 
     * @type {string}
     * @memberof ClasseUpdate
     */
    'annee_scolaire': string | null;
    /**
     * 
     * @type {number}
     * @memberof ClasseUpdate
     */
    'capacity'?: number | null;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'skip'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'limit'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Metadata
     */
    'total'?: number | null;
}
/**
 * 
 * @export
 * @interface StandardResponseClasseStatistics
 */
export interface StandardResponseClasseStatistics {
    /**
     * 
     * @type {ClasseStatistics}
     * @memberof StandardResponseClasseStatistics
     */
    'data': ClasseStatistics;
    /**
     * 
     * @type {Metadata}
     * @memberof StandardResponseClasseStatistics
     */
    'meta'?: Metadata | null;
}
/**
 * 
 * @export
 * @interface StandardResponseListClasseOut
 */
export interface StandardResponseListClasseOut {
    /**
     * 
     * @type {Array<ClasseOut>}
     * @memberof StandardResponseListClasseOut
     */
    'data': Array<ClasseOut>;
    /**
     * 
     * @type {Metadata}
     * @memberof StandardResponseListClasseOut
     */
    'meta'?: Metadata | null;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * ClassesApi - axios parameter creator
 * @export
 */
export const ClassesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Endpoint de test réservé aux administrateurs. Utilisé pour les tests d\'intégration.
         * @summary Admin Only Endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminOnlyEndpointApiV1ClassesAdminOnlyPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/classes/admin-only`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Archive une classe (soft delete).
         * @summary Archive Classe
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        archiveClasseApiV1ClassesClasseIdDelete: async (classeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('archiveClasseApiV1ClassesClasseIdDelete', 'classeId', classeId)
            const localVarPath = `/api/v1/classes/{classe_id}`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Affecte un élève à une classe.
         * @summary Assign Eleve
         * @param {ClasseEleveCreate} classeEleveCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignEleveApiV1ClassesElevesPost: async (classeEleveCreate: ClasseEleveCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeEleveCreate' is not null or undefined
            assertParamExists('assignEleveApiV1ClassesElevesPost', 'classeEleveCreate', classeEleveCreate)
            const localVarPath = `/api/v1/classes/eleves`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classeEleveCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Affecte un enseignant à une classe.
         * @summary Assign Enseignant
         * @param {ClasseEnseignantCreate} classeEnseignantCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignEnseignantApiV1ClassesEnseignantsPost: async (classeEnseignantCreate: ClasseEnseignantCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeEnseignantCreate' is not null or undefined
            assertParamExists('assignEnseignantApiV1ClassesEnseignantsPost', 'classeEnseignantCreate', classeEnseignantCreate)
            const localVarPath = `/api/v1/classes/enseignants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classeEnseignantCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Crée une nouvelle classe.
         * @summary Create Classe
         * @param {ClasseCreate} classeCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClasseApiV1ClassesPost: async (classeCreate: ClasseCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeCreate' is not null or undefined
            assertParamExists('createClasseApiV1ClassesPost', 'classeCreate', classeCreate)
            const localVarPath = `/api/v1/classes/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classeCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère l\'historique d\'audit d\'une classe.
         * @summary Get Audits
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditsApiV1ClassesClasseIdAuditsGet: async (classeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('getAuditsApiV1ClassesClasseIdAuditsGet', 'classeId', classeId)
            const localVarPath = `/api/v1/classes/{classe_id}/audits`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère une classe par son ID.
         * @summary Get Classe
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClasseApiV1ClassesClasseIdGet: async (classeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('getClasseApiV1ClassesClasseIdGet', 'classeId', classeId)
            const localVarPath = `/api/v1/classes/{classe_id}`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Liste les classes avec filtres et pagination.
         * @summary Get Classes
         * @param {string} etablissementId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {string} [nom] 
         * @param {string} [niveau] 
         * @param {boolean} [isArchived] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClassesApiV1ClassesGet: async (etablissementId: string, skip?: number, limit?: number, nom?: string, niveau?: string, isArchived?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'etablissementId' is not null or undefined
            assertParamExists('getClassesApiV1ClassesGet', 'etablissementId', etablissementId)
            const localVarPath = `/api/v1/classes/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (etablissementId !== undefined) {
                localVarQueryParameter['etablissement_id'] = etablissementId;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (nom !== undefined) {
                localVarQueryParameter['nom'] = nom;
            }

            if (niveau !== undefined) {
                localVarQueryParameter['niveau'] = niveau;
            }

            if (isArchived !== undefined) {
                localVarQueryParameter['is_archived'] = isArchived;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère tous les élèves d\'une classe.
         * @summary Get Eleves
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getElevesApiV1ClassesClasseIdElevesGet: async (classeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('getElevesApiV1ClassesClasseIdElevesGet', 'classeId', classeId)
            const localVarPath = `/api/v1/classes/{classe_id}/eleves`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère tous les enseignants d\'une classe.
         * @summary Get Enseignants
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnseignantsApiV1ClassesClasseIdEnseignantsGet: async (classeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('getEnseignantsApiV1ClassesClasseIdEnseignantsGet', 'classeId', classeId)
            const localVarPath = `/api/v1/classes/{classe_id}/enseignants`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère l\'historique complet d\'une classe.
         * @summary Get History
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoryApiV1ClassesClasseIdHistoryGet: async (classeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('getHistoryApiV1ClassesClasseIdHistoryGet', 'classeId', classeId)
            const localVarPath = `/api/v1/classes/{classe_id}/history`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Endpoint de test pour vérifier les rôles Keycloak de l\'utilisateur. Utilisé pour les tests d\'intégration.
         * @summary Get Keycloak Roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKeycloakRolesApiV1ClassesKeycloakRolesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/classes/keycloak-roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Endpoint pour récupérer les permissions de l\'utilisateur actuel. Utilisé pour les tests d\'intégration.
         * @summary Get My Permissions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyPermissionsApiV1ClassesMePermissionsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/classes/me/permissions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère les statistiques d\'une classe.
         * @summary Get Statistics
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatisticsApiV1ClassesClasseIdStatisticsGet: async (classeId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('getStatisticsApiV1ClassesClasseIdStatisticsGet', 'classeId', classeId)
            const localVarPath = `/api/v1/classes/{classe_id}/statistics`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Met à jour une classe.
         * @summary Update Classe
         * @param {string} classeId 
         * @param {ClasseUpdate} classeUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateClasseApiV1ClassesClasseIdPatch: async (classeId: string, classeUpdate: ClasseUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'classeId' is not null or undefined
            assertParamExists('updateClasseApiV1ClassesClasseIdPatch', 'classeId', classeId)
            // verify required parameter 'classeUpdate' is not null or undefined
            assertParamExists('updateClasseApiV1ClassesClasseIdPatch', 'classeUpdate', classeUpdate)
            const localVarPath = `/api/v1/classes/{classe_id}`
                .replace(`{${"classe_id"}}`, encodeURIComponent(String(classeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(classeUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClassesApi - functional programming interface
 * @export
 */
export const ClassesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClassesApiAxiosParamCreator(configuration)
    return {
        /**
         * Endpoint de test réservé aux administrateurs. Utilisé pour les tests d\'intégration.
         * @summary Admin Only Endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminOnlyEndpointApiV1ClassesAdminOnlyPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminOnlyEndpointApiV1ClassesAdminOnlyPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.adminOnlyEndpointApiV1ClassesAdminOnlyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Archive une classe (soft delete).
         * @summary Archive Classe
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async archiveClasseApiV1ClassesClasseIdDelete(classeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.archiveClasseApiV1ClassesClasseIdDelete(classeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.archiveClasseApiV1ClassesClasseIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Affecte un élève à une classe.
         * @summary Assign Eleve
         * @param {ClasseEleveCreate} classeEleveCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignEleveApiV1ClassesElevesPost(classeEleveCreate: ClasseEleveCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClasseEleveOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignEleveApiV1ClassesElevesPost(classeEleveCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.assignEleveApiV1ClassesElevesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Affecte un enseignant à une classe.
         * @summary Assign Enseignant
         * @param {ClasseEnseignantCreate} classeEnseignantCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignEnseignantApiV1ClassesEnseignantsPost(classeEnseignantCreate: ClasseEnseignantCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClasseEnseignantOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignEnseignantApiV1ClassesEnseignantsPost(classeEnseignantCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.assignEnseignantApiV1ClassesEnseignantsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Crée une nouvelle classe.
         * @summary Create Classe
         * @param {ClasseCreate} classeCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createClasseApiV1ClassesPost(classeCreate: ClasseCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClasseOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createClasseApiV1ClassesPost(classeCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.createClasseApiV1ClassesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère l\'historique d\'audit d\'une classe.
         * @summary Get Audits
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuditsApiV1ClassesClasseIdAuditsGet(classeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ClasseAuditOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuditsApiV1ClassesClasseIdAuditsGet(classeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getAuditsApiV1ClassesClasseIdAuditsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère une classe par son ID.
         * @summary Get Classe
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClasseApiV1ClassesClasseIdGet(classeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClasseOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClasseApiV1ClassesClasseIdGet(classeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getClasseApiV1ClassesClasseIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Liste les classes avec filtres et pagination.
         * @summary Get Classes
         * @param {string} etablissementId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {string} [nom] 
         * @param {string} [niveau] 
         * @param {boolean} [isArchived] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClassesApiV1ClassesGet(etablissementId: string, skip?: number, limit?: number, nom?: string, niveau?: string, isArchived?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardResponseListClasseOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getClassesApiV1ClassesGet(etablissementId, skip, limit, nom, niveau, isArchived, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getClassesApiV1ClassesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère tous les élèves d\'une classe.
         * @summary Get Eleves
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getElevesApiV1ClassesClasseIdElevesGet(classeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ClasseEleveOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getElevesApiV1ClassesClasseIdElevesGet(classeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getElevesApiV1ClassesClasseIdElevesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère tous les enseignants d\'une classe.
         * @summary Get Enseignants
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnseignantsApiV1ClassesClasseIdEnseignantsGet(classeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ClasseEnseignantOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnseignantsApiV1ClassesClasseIdEnseignantsGet(classeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getEnseignantsApiV1ClassesClasseIdEnseignantsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère l\'historique complet d\'une classe.
         * @summary Get History
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistoryApiV1ClassesClasseIdHistoryGet(classeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ClasseHistoryOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistoryApiV1ClassesClasseIdHistoryGet(classeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getHistoryApiV1ClassesClasseIdHistoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Endpoint de test pour vérifier les rôles Keycloak de l\'utilisateur. Utilisé pour les tests d\'intégration.
         * @summary Get Keycloak Roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKeycloakRolesApiV1ClassesKeycloakRolesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKeycloakRolesApiV1ClassesKeycloakRolesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getKeycloakRolesApiV1ClassesKeycloakRolesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Endpoint pour récupérer les permissions de l\'utilisateur actuel. Utilisé pour les tests d\'intégration.
         * @summary Get My Permissions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyPermissionsApiV1ClassesMePermissionsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyPermissionsApiV1ClassesMePermissionsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getMyPermissionsApiV1ClassesMePermissionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère les statistiques d\'une classe.
         * @summary Get Statistics
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatisticsApiV1ClassesClasseIdStatisticsGet(classeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StandardResponseClasseStatistics>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatisticsApiV1ClassesClasseIdStatisticsGet(classeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.getStatisticsApiV1ClassesClasseIdStatisticsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Met à jour une classe.
         * @summary Update Classe
         * @param {string} classeId 
         * @param {ClasseUpdate} classeUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateClasseApiV1ClassesClasseIdPatch(classeId: string, classeUpdate: ClasseUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClasseOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateClasseApiV1ClassesClasseIdPatch(classeId, classeUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ClassesApi.updateClasseApiV1ClassesClasseIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ClassesApi - factory interface
 * @export
 */
export const ClassesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClassesApiFp(configuration)
    return {
        /**
         * Endpoint de test réservé aux administrateurs. Utilisé pour les tests d\'intégration.
         * @summary Admin Only Endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminOnlyEndpointApiV1ClassesAdminOnlyPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.adminOnlyEndpointApiV1ClassesAdminOnlyPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Archive une classe (soft delete).
         * @summary Archive Classe
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        archiveClasseApiV1ClassesClasseIdDelete(classeId: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.archiveClasseApiV1ClassesClasseIdDelete(classeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Affecte un élève à une classe.
         * @summary Assign Eleve
         * @param {ClasseEleveCreate} classeEleveCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignEleveApiV1ClassesElevesPost(classeEleveCreate: ClasseEleveCreate, options?: RawAxiosRequestConfig): AxiosPromise<ClasseEleveOut> {
            return localVarFp.assignEleveApiV1ClassesElevesPost(classeEleveCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Affecte un enseignant à une classe.
         * @summary Assign Enseignant
         * @param {ClasseEnseignantCreate} classeEnseignantCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignEnseignantApiV1ClassesEnseignantsPost(classeEnseignantCreate: ClasseEnseignantCreate, options?: RawAxiosRequestConfig): AxiosPromise<ClasseEnseignantOut> {
            return localVarFp.assignEnseignantApiV1ClassesEnseignantsPost(classeEnseignantCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Crée une nouvelle classe.
         * @summary Create Classe
         * @param {ClasseCreate} classeCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createClasseApiV1ClassesPost(classeCreate: ClasseCreate, options?: RawAxiosRequestConfig): AxiosPromise<ClasseOut> {
            return localVarFp.createClasseApiV1ClassesPost(classeCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère l\'historique d\'audit d\'une classe.
         * @summary Get Audits
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditsApiV1ClassesClasseIdAuditsGet(classeId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ClasseAuditOut>> {
            return localVarFp.getAuditsApiV1ClassesClasseIdAuditsGet(classeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère une classe par son ID.
         * @summary Get Classe
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClasseApiV1ClassesClasseIdGet(classeId: string, options?: RawAxiosRequestConfig): AxiosPromise<ClasseOut> {
            return localVarFp.getClasseApiV1ClassesClasseIdGet(classeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Liste les classes avec filtres et pagination.
         * @summary Get Classes
         * @param {string} etablissementId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {string} [nom] 
         * @param {string} [niveau] 
         * @param {boolean} [isArchived] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClassesApiV1ClassesGet(etablissementId: string, skip?: number, limit?: number, nom?: string, niveau?: string, isArchived?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<StandardResponseListClasseOut> {
            return localVarFp.getClassesApiV1ClassesGet(etablissementId, skip, limit, nom, niveau, isArchived, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère tous les élèves d\'une classe.
         * @summary Get Eleves
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getElevesApiV1ClassesClasseIdElevesGet(classeId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ClasseEleveOut>> {
            return localVarFp.getElevesApiV1ClassesClasseIdElevesGet(classeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère tous les enseignants d\'une classe.
         * @summary Get Enseignants
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnseignantsApiV1ClassesClasseIdEnseignantsGet(classeId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ClasseEnseignantOut>> {
            return localVarFp.getEnseignantsApiV1ClassesClasseIdEnseignantsGet(classeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère l\'historique complet d\'une classe.
         * @summary Get History
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoryApiV1ClassesClasseIdHistoryGet(classeId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ClasseHistoryOut>> {
            return localVarFp.getHistoryApiV1ClassesClasseIdHistoryGet(classeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Endpoint de test pour vérifier les rôles Keycloak de l\'utilisateur. Utilisé pour les tests d\'intégration.
         * @summary Get Keycloak Roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKeycloakRolesApiV1ClassesKeycloakRolesGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getKeycloakRolesApiV1ClassesKeycloakRolesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Endpoint pour récupérer les permissions de l\'utilisateur actuel. Utilisé pour les tests d\'intégration.
         * @summary Get My Permissions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyPermissionsApiV1ClassesMePermissionsGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getMyPermissionsApiV1ClassesMePermissionsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère les statistiques d\'une classe.
         * @summary Get Statistics
         * @param {string} classeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatisticsApiV1ClassesClasseIdStatisticsGet(classeId: string, options?: RawAxiosRequestConfig): AxiosPromise<StandardResponseClasseStatistics> {
            return localVarFp.getStatisticsApiV1ClassesClasseIdStatisticsGet(classeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Met à jour une classe.
         * @summary Update Classe
         * @param {string} classeId 
         * @param {ClasseUpdate} classeUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateClasseApiV1ClassesClasseIdPatch(classeId: string, classeUpdate: ClasseUpdate, options?: RawAxiosRequestConfig): AxiosPromise<ClasseOut> {
            return localVarFp.updateClasseApiV1ClassesClasseIdPatch(classeId, classeUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ClassesApi - object-oriented interface
 * @export
 * @class ClassesApi
 * @extends {BaseAPI}
 */
export class ClassesApi extends BaseAPI {
    /**
     * Endpoint de test réservé aux administrateurs. Utilisé pour les tests d\'intégration.
     * @summary Admin Only Endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public adminOnlyEndpointApiV1ClassesAdminOnlyPost(options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).adminOnlyEndpointApiV1ClassesAdminOnlyPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Archive une classe (soft delete).
     * @summary Archive Classe
     * @param {string} classeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public archiveClasseApiV1ClassesClasseIdDelete(classeId: string, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).archiveClasseApiV1ClassesClasseIdDelete(classeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Affecte un élève à une classe.
     * @summary Assign Eleve
     * @param {ClasseEleveCreate} classeEleveCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public assignEleveApiV1ClassesElevesPost(classeEleveCreate: ClasseEleveCreate, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).assignEleveApiV1ClassesElevesPost(classeEleveCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Affecte un enseignant à une classe.
     * @summary Assign Enseignant
     * @param {ClasseEnseignantCreate} classeEnseignantCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public assignEnseignantApiV1ClassesEnseignantsPost(classeEnseignantCreate: ClasseEnseignantCreate, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).assignEnseignantApiV1ClassesEnseignantsPost(classeEnseignantCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Crée une nouvelle classe.
     * @summary Create Classe
     * @param {ClasseCreate} classeCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public createClasseApiV1ClassesPost(classeCreate: ClasseCreate, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).createClasseApiV1ClassesPost(classeCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère l\'historique d\'audit d\'une classe.
     * @summary Get Audits
     * @param {string} classeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getAuditsApiV1ClassesClasseIdAuditsGet(classeId: string, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getAuditsApiV1ClassesClasseIdAuditsGet(classeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère une classe par son ID.
     * @summary Get Classe
     * @param {string} classeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getClasseApiV1ClassesClasseIdGet(classeId: string, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getClasseApiV1ClassesClasseIdGet(classeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Liste les classes avec filtres et pagination.
     * @summary Get Classes
     * @param {string} etablissementId 
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {string} [nom] 
     * @param {string} [niveau] 
     * @param {boolean} [isArchived] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getClassesApiV1ClassesGet(etablissementId: string, skip?: number, limit?: number, nom?: string, niveau?: string, isArchived?: boolean, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getClassesApiV1ClassesGet(etablissementId, skip, limit, nom, niveau, isArchived, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère tous les élèves d\'une classe.
     * @summary Get Eleves
     * @param {string} classeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getElevesApiV1ClassesClasseIdElevesGet(classeId: string, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getElevesApiV1ClassesClasseIdElevesGet(classeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère tous les enseignants d\'une classe.
     * @summary Get Enseignants
     * @param {string} classeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getEnseignantsApiV1ClassesClasseIdEnseignantsGet(classeId: string, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getEnseignantsApiV1ClassesClasseIdEnseignantsGet(classeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère l\'historique complet d\'une classe.
     * @summary Get History
     * @param {string} classeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getHistoryApiV1ClassesClasseIdHistoryGet(classeId: string, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getHistoryApiV1ClassesClasseIdHistoryGet(classeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Endpoint de test pour vérifier les rôles Keycloak de l\'utilisateur. Utilisé pour les tests d\'intégration.
     * @summary Get Keycloak Roles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getKeycloakRolesApiV1ClassesKeycloakRolesGet(options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getKeycloakRolesApiV1ClassesKeycloakRolesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Endpoint pour récupérer les permissions de l\'utilisateur actuel. Utilisé pour les tests d\'intégration.
     * @summary Get My Permissions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getMyPermissionsApiV1ClassesMePermissionsGet(options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getMyPermissionsApiV1ClassesMePermissionsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère les statistiques d\'une classe.
     * @summary Get Statistics
     * @param {string} classeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public getStatisticsApiV1ClassesClasseIdStatisticsGet(classeId: string, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).getStatisticsApiV1ClassesClasseIdStatisticsGet(classeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Met à jour une classe.
     * @summary Update Classe
     * @param {string} classeId 
     * @param {ClasseUpdate} classeUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClassesApi
     */
    public updateClasseApiV1ClassesClasseIdPatch(classeId: string, classeUpdate: ClasseUpdate, options?: RawAxiosRequestConfig) {
        return ClassesApiFp(this.configuration).updateClasseApiV1ClassesClasseIdPatch(classeId, classeUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Vérifie l\'état de santé du service.
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Endpoint racine de l\'application.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Vérifie l\'état de santé du service.
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthCheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Endpoint racine de l\'application.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.rootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Vérifie l\'état de santé du service.
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Endpoint racine de l\'application.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Vérifie l\'état de santé du service.
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheckHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Endpoint racine de l\'application.
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Vérifie l\'état de santé du service.  Returns:     dict: État du service
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiV1HealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * Vérifie l\'état de santé du service.  Returns:     dict: État du service
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckApiV1HealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckApiV1HealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheckApiV1HealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * Vérifie l\'état de santé du service.  Returns:     dict: État du service
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiV1HealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckApiV1HealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * Vérifie l\'état de santé du service.  Returns:     dict: État du service
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthCheckApiV1HealthGet(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheckApiV1HealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



