/* tslint:disable */
/* eslint-disable */
/**
 * Admission Service API
 * API pour la gestion des demandes d\'admission
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Schéma pour la requête de création d\'une admission (avec CAPTCHA)
 * @export
 * @interface AdmissionCreateRequest
 */
export interface AdmissionCreateRequest {
    /**
     * Nom complet de l\'élève
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'student_name': string;
    /**
     * Date de naissance de l\'élève
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'student_birthdate': string;
    /**
     * Classe demandée
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'class_requested': string;
    /**
     * Nom du parent/tuteur
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'parent_name': string;
    /**
     * Contact du parent (email ou téléphone)
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'parent_contact': string;
    /**
     * 
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'student_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'student_phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'parent_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'parent_phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'notes'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdmissionCreateRequest
     */
    'attachments'?: Array<string> | null;
    /**
     * Token reCAPTCHA v3 pour validation anti-spam
     * @type {string}
     * @memberof AdmissionCreateRequest
     */
    'captcha_token': string;
}
/**
 * Schéma de réponse pour la liste des admissions avec pagination
 * @export
 * @interface AdmissionListResponse
 */
export interface AdmissionListResponse {
    /**
     * 
     * @type {Array<AdmissionResponse>}
     * @memberof AdmissionListResponse
     */
    'items': Array<AdmissionResponse>;
    /**
     * 
     * @type {number}
     * @memberof AdmissionListResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof AdmissionListResponse
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof AdmissionListResponse
     */
    'limit': number;
    /**
     * 
     * @type {number}
     * @memberof AdmissionListResponse
     */
    'pages': number;
}
/**
 * Schéma de réponse pour une admission
 * @export
 * @interface AdmissionResponse
 */
export interface AdmissionResponse {
    /**
     * Nom complet de l\'élève
     * @type {string}
     * @memberof AdmissionResponse
     */
    'student_name': string;
    /**
     * Date de naissance de l\'élève
     * @type {string}
     * @memberof AdmissionResponse
     */
    'student_birthdate': string;
    /**
     * Classe demandée
     * @type {string}
     * @memberof AdmissionResponse
     */
    'class_requested': string;
    /**
     * Nom du parent/tuteur
     * @type {string}
     * @memberof AdmissionResponse
     */
    'parent_name': string;
    /**
     * Contact du parent (email ou téléphone)
     * @type {string}
     * @memberof AdmissionResponse
     */
    'parent_contact': string;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'student_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'student_phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'parent_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'parent_phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'notes'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdmissionResponse
     */
    'attachments'?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof AdmissionResponse
     */
    'id': number;
    /**
     * 
     * @type {AdmissionStatus}
     * @memberof AdmissionResponse
     */
    'status': AdmissionStatus;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'updated_at': string;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'tenant_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'admin_notes'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'reviewed_by'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionResponse
     */
    'reviewed_at'?: string | null;
}


/**
 * Énumération des statuts possibles pour une admission
 * @export
 * @enum {string}
 */

export const AdmissionStatus = {
    Pending: 'PENDING',
    Accepted: 'ACCEPTED',
    Rejected: 'REJECTED',
    Waitlist: 'WAITLIST'
} as const;

export type AdmissionStatus = typeof AdmissionStatus[keyof typeof AdmissionStatus];


/**
 * Schéma pour la mise à jour du statut uniquement
 * @export
 * @interface AdmissionStatusUpdate
 */
export interface AdmissionStatusUpdate {
    /**
     * Nouveau statut de l\'admission
     * @type {AdmissionStatus}
     * @memberof AdmissionStatusUpdate
     */
    'status': AdmissionStatus;
    /**
     * 
     * @type {string}
     * @memberof AdmissionStatusUpdate
     */
    'admin_notes'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionStatusUpdate
     */
    'reviewed_by'?: string | null;
}


/**
 * Schéma pour la mise à jour d\'une admission
 * @export
 * @interface AdmissionUpdate
 */
export interface AdmissionUpdate {
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'student_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'student_birthdate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'class_requested'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'parent_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'parent_contact'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'student_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'student_phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'parent_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'parent_phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdmissionUpdate
     */
    'notes'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdmissionUpdate
     */
    'attachments'?: Array<string> | null;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * AdmissionsApi - axios parameter creator
 * @export
 */
export const AdmissionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Créer une nouvelle admission.  **Authentification requise** : Headers X-User, X-Roles, X-Etab obligatoires.  - **student_name**: Nom complet de l\'élève (requis) - **student_birthdate**: Date de naissance de l\'élève (requis) - **class_requested**: Classe demandée (requis) - **parent_name**: Nom du parent/tuteur (requis) - **parent_contact**: Contact du parent (email ou téléphone) (requis) - **student_email**: Email de l\'élève (optionnel) - **student_phone**: Téléphone de l\'élève (optionnel) - **parent_email**: Email du parent (optionnel) - **parent_phone**: Téléphone du parent (optionnel) - **notes**: Notes additionnelles (optionnel) - **attachments**: Liste des chemins des fichiers joints (optionnel) - **captcha_token**: Token reCAPTCHA v3 pour validation anti-spam (requis)  Le statut sera automatiquement défini sur \'PENDING\'. L\'admission sera automatiquement associée à l\'établissement (tenant_id) de l\'utilisateur.
         * @summary Create Admission
         * @param {AdmissionCreateRequest} admissionCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAdmissionApiV1AdmissionsPost: async (admissionCreateRequest: AdmissionCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'admissionCreateRequest' is not null or undefined
            assertParamExists('createAdmissionApiV1AdmissionsPost', 'admissionCreateRequest', admissionCreateRequest)
            const localVarPath = `/api/v1/admissions/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(admissionCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Supprimer une admission.  - **admission_id**: ID de l\'admission à supprimer  Retourne une erreur 404 si l\'admission n\'existe pas.
         * @summary Delete Admission
         * @param {number} admissionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAdmissionApiV1AdmissionsAdmissionIdDelete: async (admissionId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'admissionId' is not null or undefined
            assertParamExists('deleteAdmissionApiV1AdmissionsAdmissionIdDelete', 'admissionId', admissionId)
            const localVarPath = `/api/v1/admissions/{admission_id}`
                .replace(`{${"admission_id"}}`, encodeURIComponent(String(admissionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupérer les détails d\'une admission spécifique.  - **admission_id**: ID de l\'admission à récupérer  Retourne une erreur 404 si l\'admission n\'existe pas.
         * @summary Get Admission
         * @param {number} admissionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdmissionApiV1AdmissionsAdmissionIdGet: async (admissionId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'admissionId' is not null or undefined
            assertParamExists('getAdmissionApiV1AdmissionsAdmissionIdGet', 'admissionId', admissionId)
            const localVarPath = `/api/v1/admissions/{admission_id}`
                .replace(`{${"admission_id"}}`, encodeURIComponent(String(admissionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupérer les statistiques des admissions (filtrées par établissement).  Retourne le nombre total d\'admissions et la répartition par statut pour l\'établissement de l\'utilisateur connecté.
         * @summary Get Admission Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdmissionStatsApiV1AdmissionsStatsSummaryGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admissions/stats/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupérer la liste des admissions avec pagination et filtres.  - **page**: Numéro de page (défaut: 1) - **limit**: Nombre d\'éléments par page (défaut: 10, max: 100) - **status**: Filtrer par statut (PENDING, ACCEPTED, REJECTED, WAITLIST) - **class_requested**: Filtrer par classe demandée - **student_name**: Filtrer par nom d\'élève - **parent_name**: Filtrer par nom de parent  Les résultats sont filtrés par établissement (tenant_id) automatiquement. Les résultats sont triés par date de création (plus récent en premier).
         * @summary Get Admissions
         * @param {number} [page] Numéro de page
         * @param {number} [limit] Nombre d\&#39;éléments par page
         * @param {AdmissionStatus | null} [statusFilter] Filtrer par statut
         * @param {string | null} [classRequested] Filtrer par classe demandée
         * @param {string | null} [studentName] Filtrer par nom d\&#39;élève
         * @param {string | null} [parentName] Filtrer par nom de parent
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdmissionsApiV1AdmissionsGet: async (page?: number, limit?: number, statusFilter?: AdmissionStatus | null, classRequested?: string | null, studentName?: string | null, parentName?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/admissions/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (statusFilter !== undefined) {
                localVarQueryParameter['status_filter'] = statusFilter;
            }

            if (classRequested !== undefined) {
                localVarQueryParameter['class_requested'] = classRequested;
            }

            if (studentName !== undefined) {
                localVarQueryParameter['student_name'] = studentName;
            }

            if (parentName !== undefined) {
                localVarQueryParameter['parent_name'] = parentName;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mettre à jour une admission complète.  - **admission_id**: ID de l\'admission à mettre à jour - Tous les champs de l\'admission peuvent être mis à jour  Met automatiquement à jour le champ `updated_at`.
         * @summary Update Admission
         * @param {number} admissionId 
         * @param {AdmissionUpdate} admissionUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdmissionApiV1AdmissionsAdmissionIdPut: async (admissionId: number, admissionUpdate: AdmissionUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'admissionId' is not null or undefined
            assertParamExists('updateAdmissionApiV1AdmissionsAdmissionIdPut', 'admissionId', admissionId)
            // verify required parameter 'admissionUpdate' is not null or undefined
            assertParamExists('updateAdmissionApiV1AdmissionsAdmissionIdPut', 'admissionUpdate', admissionUpdate)
            const localVarPath = `/api/v1/admissions/{admission_id}`
                .replace(`{${"admission_id"}}`, encodeURIComponent(String(admissionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(admissionUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mettre à jour le statut d\'une admission.  - **admission_id**: ID de l\'admission à mettre à jour - **status**: Nouveau statut (ACCEPTED, REJECTED, WAITLIST) - **admin_notes**: Notes de l\'administrateur (optionnel) - **reviewed_by**: Nom de l\'administrateur (optionnel)  Met automatiquement à jour les champs `reviewed_at` et `updated_at`.
         * @summary Update Admission Status
         * @param {number} admissionId 
         * @param {AdmissionStatusUpdate} admissionStatusUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch: async (admissionId: number, admissionStatusUpdate: AdmissionStatusUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'admissionId' is not null or undefined
            assertParamExists('updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch', 'admissionId', admissionId)
            // verify required parameter 'admissionStatusUpdate' is not null or undefined
            assertParamExists('updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch', 'admissionStatusUpdate', admissionStatusUpdate)
            const localVarPath = `/api/v1/admissions/{admission_id}/status`
                .replace(`{${"admission_id"}}`, encodeURIComponent(String(admissionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(admissionStatusUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdmissionsApi - functional programming interface
 * @export
 */
export const AdmissionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdmissionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Créer une nouvelle admission.  **Authentification requise** : Headers X-User, X-Roles, X-Etab obligatoires.  - **student_name**: Nom complet de l\'élève (requis) - **student_birthdate**: Date de naissance de l\'élève (requis) - **class_requested**: Classe demandée (requis) - **parent_name**: Nom du parent/tuteur (requis) - **parent_contact**: Contact du parent (email ou téléphone) (requis) - **student_email**: Email de l\'élève (optionnel) - **student_phone**: Téléphone de l\'élève (optionnel) - **parent_email**: Email du parent (optionnel) - **parent_phone**: Téléphone du parent (optionnel) - **notes**: Notes additionnelles (optionnel) - **attachments**: Liste des chemins des fichiers joints (optionnel) - **captcha_token**: Token reCAPTCHA v3 pour validation anti-spam (requis)  Le statut sera automatiquement défini sur \'PENDING\'. L\'admission sera automatiquement associée à l\'établissement (tenant_id) de l\'utilisateur.
         * @summary Create Admission
         * @param {AdmissionCreateRequest} admissionCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAdmissionApiV1AdmissionsPost(admissionCreateRequest: AdmissionCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdmissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAdmissionApiV1AdmissionsPost(admissionCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdmissionsApi.createAdmissionApiV1AdmissionsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Supprimer une admission.  - **admission_id**: ID de l\'admission à supprimer  Retourne une erreur 404 si l\'admission n\'existe pas.
         * @summary Delete Admission
         * @param {number} admissionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAdmissionApiV1AdmissionsAdmissionIdDelete(admissionId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAdmissionApiV1AdmissionsAdmissionIdDelete(admissionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdmissionsApi.deleteAdmissionApiV1AdmissionsAdmissionIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupérer les détails d\'une admission spécifique.  - **admission_id**: ID de l\'admission à récupérer  Retourne une erreur 404 si l\'admission n\'existe pas.
         * @summary Get Admission
         * @param {number} admissionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdmissionApiV1AdmissionsAdmissionIdGet(admissionId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdmissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdmissionApiV1AdmissionsAdmissionIdGet(admissionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdmissionsApi.getAdmissionApiV1AdmissionsAdmissionIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupérer les statistiques des admissions (filtrées par établissement).  Retourne le nombre total d\'admissions et la répartition par statut pour l\'établissement de l\'utilisateur connecté.
         * @summary Get Admission Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdmissionStatsApiV1AdmissionsStatsSummaryGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdmissionStatsApiV1AdmissionsStatsSummaryGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdmissionsApi.getAdmissionStatsApiV1AdmissionsStatsSummaryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupérer la liste des admissions avec pagination et filtres.  - **page**: Numéro de page (défaut: 1) - **limit**: Nombre d\'éléments par page (défaut: 10, max: 100) - **status**: Filtrer par statut (PENDING, ACCEPTED, REJECTED, WAITLIST) - **class_requested**: Filtrer par classe demandée - **student_name**: Filtrer par nom d\'élève - **parent_name**: Filtrer par nom de parent  Les résultats sont filtrés par établissement (tenant_id) automatiquement. Les résultats sont triés par date de création (plus récent en premier).
         * @summary Get Admissions
         * @param {number} [page] Numéro de page
         * @param {number} [limit] Nombre d\&#39;éléments par page
         * @param {AdmissionStatus | null} [statusFilter] Filtrer par statut
         * @param {string | null} [classRequested] Filtrer par classe demandée
         * @param {string | null} [studentName] Filtrer par nom d\&#39;élève
         * @param {string | null} [parentName] Filtrer par nom de parent
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdmissionsApiV1AdmissionsGet(page?: number, limit?: number, statusFilter?: AdmissionStatus | null, classRequested?: string | null, studentName?: string | null, parentName?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdmissionListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdmissionsApiV1AdmissionsGet(page, limit, statusFilter, classRequested, studentName, parentName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdmissionsApi.getAdmissionsApiV1AdmissionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Mettre à jour une admission complète.  - **admission_id**: ID de l\'admission à mettre à jour - Tous les champs de l\'admission peuvent être mis à jour  Met automatiquement à jour le champ `updated_at`.
         * @summary Update Admission
         * @param {number} admissionId 
         * @param {AdmissionUpdate} admissionUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAdmissionApiV1AdmissionsAdmissionIdPut(admissionId: number, admissionUpdate: AdmissionUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdmissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAdmissionApiV1AdmissionsAdmissionIdPut(admissionId, admissionUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdmissionsApi.updateAdmissionApiV1AdmissionsAdmissionIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Mettre à jour le statut d\'une admission.  - **admission_id**: ID de l\'admission à mettre à jour - **status**: Nouveau statut (ACCEPTED, REJECTED, WAITLIST) - **admin_notes**: Notes de l\'administrateur (optionnel) - **reviewed_by**: Nom de l\'administrateur (optionnel)  Met automatiquement à jour les champs `reviewed_at` et `updated_at`.
         * @summary Update Admission Status
         * @param {number} admissionId 
         * @param {AdmissionStatusUpdate} admissionStatusUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch(admissionId: number, admissionStatusUpdate: AdmissionStatusUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdmissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch(admissionId, admissionStatusUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdmissionsApi.updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdmissionsApi - factory interface
 * @export
 */
export const AdmissionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdmissionsApiFp(configuration)
    return {
        /**
         * Créer une nouvelle admission.  **Authentification requise** : Headers X-User, X-Roles, X-Etab obligatoires.  - **student_name**: Nom complet de l\'élève (requis) - **student_birthdate**: Date de naissance de l\'élève (requis) - **class_requested**: Classe demandée (requis) - **parent_name**: Nom du parent/tuteur (requis) - **parent_contact**: Contact du parent (email ou téléphone) (requis) - **student_email**: Email de l\'élève (optionnel) - **student_phone**: Téléphone de l\'élève (optionnel) - **parent_email**: Email du parent (optionnel) - **parent_phone**: Téléphone du parent (optionnel) - **notes**: Notes additionnelles (optionnel) - **attachments**: Liste des chemins des fichiers joints (optionnel) - **captcha_token**: Token reCAPTCHA v3 pour validation anti-spam (requis)  Le statut sera automatiquement défini sur \'PENDING\'. L\'admission sera automatiquement associée à l\'établissement (tenant_id) de l\'utilisateur.
         * @summary Create Admission
         * @param {AdmissionCreateRequest} admissionCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAdmissionApiV1AdmissionsPost(admissionCreateRequest: AdmissionCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdmissionResponse> {
            return localVarFp.createAdmissionApiV1AdmissionsPost(admissionCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Supprimer une admission.  - **admission_id**: ID de l\'admission à supprimer  Retourne une erreur 404 si l\'admission n\'existe pas.
         * @summary Delete Admission
         * @param {number} admissionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAdmissionApiV1AdmissionsAdmissionIdDelete(admissionId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteAdmissionApiV1AdmissionsAdmissionIdDelete(admissionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupérer les détails d\'une admission spécifique.  - **admission_id**: ID de l\'admission à récupérer  Retourne une erreur 404 si l\'admission n\'existe pas.
         * @summary Get Admission
         * @param {number} admissionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdmissionApiV1AdmissionsAdmissionIdGet(admissionId: number, options?: RawAxiosRequestConfig): AxiosPromise<AdmissionResponse> {
            return localVarFp.getAdmissionApiV1AdmissionsAdmissionIdGet(admissionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupérer les statistiques des admissions (filtrées par établissement).  Retourne le nombre total d\'admissions et la répartition par statut pour l\'établissement de l\'utilisateur connecté.
         * @summary Get Admission Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdmissionStatsApiV1AdmissionsStatsSummaryGet(options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getAdmissionStatsApiV1AdmissionsStatsSummaryGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Récupérer la liste des admissions avec pagination et filtres.  - **page**: Numéro de page (défaut: 1) - **limit**: Nombre d\'éléments par page (défaut: 10, max: 100) - **status**: Filtrer par statut (PENDING, ACCEPTED, REJECTED, WAITLIST) - **class_requested**: Filtrer par classe demandée - **student_name**: Filtrer par nom d\'élève - **parent_name**: Filtrer par nom de parent  Les résultats sont filtrés par établissement (tenant_id) automatiquement. Les résultats sont triés par date de création (plus récent en premier).
         * @summary Get Admissions
         * @param {number} [page] Numéro de page
         * @param {number} [limit] Nombre d\&#39;éléments par page
         * @param {AdmissionStatus | null} [statusFilter] Filtrer par statut
         * @param {string | null} [classRequested] Filtrer par classe demandée
         * @param {string | null} [studentName] Filtrer par nom d\&#39;élève
         * @param {string | null} [parentName] Filtrer par nom de parent
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdmissionsApiV1AdmissionsGet(page?: number, limit?: number, statusFilter?: AdmissionStatus | null, classRequested?: string | null, studentName?: string | null, parentName?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<AdmissionListResponse> {
            return localVarFp.getAdmissionsApiV1AdmissionsGet(page, limit, statusFilter, classRequested, studentName, parentName, options).then((request) => request(axios, basePath));
        },
        /**
         * Mettre à jour une admission complète.  - **admission_id**: ID de l\'admission à mettre à jour - Tous les champs de l\'admission peuvent être mis à jour  Met automatiquement à jour le champ `updated_at`.
         * @summary Update Admission
         * @param {number} admissionId 
         * @param {AdmissionUpdate} admissionUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdmissionApiV1AdmissionsAdmissionIdPut(admissionId: number, admissionUpdate: AdmissionUpdate, options?: RawAxiosRequestConfig): AxiosPromise<AdmissionResponse> {
            return localVarFp.updateAdmissionApiV1AdmissionsAdmissionIdPut(admissionId, admissionUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * Mettre à jour le statut d\'une admission.  - **admission_id**: ID de l\'admission à mettre à jour - **status**: Nouveau statut (ACCEPTED, REJECTED, WAITLIST) - **admin_notes**: Notes de l\'administrateur (optionnel) - **reviewed_by**: Nom de l\'administrateur (optionnel)  Met automatiquement à jour les champs `reviewed_at` et `updated_at`.
         * @summary Update Admission Status
         * @param {number} admissionId 
         * @param {AdmissionStatusUpdate} admissionStatusUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch(admissionId: number, admissionStatusUpdate: AdmissionStatusUpdate, options?: RawAxiosRequestConfig): AxiosPromise<AdmissionResponse> {
            return localVarFp.updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch(admissionId, admissionStatusUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdmissionsApi - object-oriented interface
 * @export
 * @class AdmissionsApi
 * @extends {BaseAPI}
 */
export class AdmissionsApi extends BaseAPI {
    /**
     * Créer une nouvelle admission.  **Authentification requise** : Headers X-User, X-Roles, X-Etab obligatoires.  - **student_name**: Nom complet de l\'élève (requis) - **student_birthdate**: Date de naissance de l\'élève (requis) - **class_requested**: Classe demandée (requis) - **parent_name**: Nom du parent/tuteur (requis) - **parent_contact**: Contact du parent (email ou téléphone) (requis) - **student_email**: Email de l\'élève (optionnel) - **student_phone**: Téléphone de l\'élève (optionnel) - **parent_email**: Email du parent (optionnel) - **parent_phone**: Téléphone du parent (optionnel) - **notes**: Notes additionnelles (optionnel) - **attachments**: Liste des chemins des fichiers joints (optionnel) - **captcha_token**: Token reCAPTCHA v3 pour validation anti-spam (requis)  Le statut sera automatiquement défini sur \'PENDING\'. L\'admission sera automatiquement associée à l\'établissement (tenant_id) de l\'utilisateur.
     * @summary Create Admission
     * @param {AdmissionCreateRequest} admissionCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdmissionsApi
     */
    public createAdmissionApiV1AdmissionsPost(admissionCreateRequest: AdmissionCreateRequest, options?: RawAxiosRequestConfig) {
        return AdmissionsApiFp(this.configuration).createAdmissionApiV1AdmissionsPost(admissionCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Supprimer une admission.  - **admission_id**: ID de l\'admission à supprimer  Retourne une erreur 404 si l\'admission n\'existe pas.
     * @summary Delete Admission
     * @param {number} admissionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdmissionsApi
     */
    public deleteAdmissionApiV1AdmissionsAdmissionIdDelete(admissionId: number, options?: RawAxiosRequestConfig) {
        return AdmissionsApiFp(this.configuration).deleteAdmissionApiV1AdmissionsAdmissionIdDelete(admissionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupérer les détails d\'une admission spécifique.  - **admission_id**: ID de l\'admission à récupérer  Retourne une erreur 404 si l\'admission n\'existe pas.
     * @summary Get Admission
     * @param {number} admissionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdmissionsApi
     */
    public getAdmissionApiV1AdmissionsAdmissionIdGet(admissionId: number, options?: RawAxiosRequestConfig) {
        return AdmissionsApiFp(this.configuration).getAdmissionApiV1AdmissionsAdmissionIdGet(admissionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupérer les statistiques des admissions (filtrées par établissement).  Retourne le nombre total d\'admissions et la répartition par statut pour l\'établissement de l\'utilisateur connecté.
     * @summary Get Admission Stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdmissionsApi
     */
    public getAdmissionStatsApiV1AdmissionsStatsSummaryGet(options?: RawAxiosRequestConfig) {
        return AdmissionsApiFp(this.configuration).getAdmissionStatsApiV1AdmissionsStatsSummaryGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupérer la liste des admissions avec pagination et filtres.  - **page**: Numéro de page (défaut: 1) - **limit**: Nombre d\'éléments par page (défaut: 10, max: 100) - **status**: Filtrer par statut (PENDING, ACCEPTED, REJECTED, WAITLIST) - **class_requested**: Filtrer par classe demandée - **student_name**: Filtrer par nom d\'élève - **parent_name**: Filtrer par nom de parent  Les résultats sont filtrés par établissement (tenant_id) automatiquement. Les résultats sont triés par date de création (plus récent en premier).
     * @summary Get Admissions
     * @param {number} [page] Numéro de page
     * @param {number} [limit] Nombre d\&#39;éléments par page
     * @param {AdmissionStatus | null} [statusFilter] Filtrer par statut
     * @param {string | null} [classRequested] Filtrer par classe demandée
     * @param {string | null} [studentName] Filtrer par nom d\&#39;élève
     * @param {string | null} [parentName] Filtrer par nom de parent
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdmissionsApi
     */
    public getAdmissionsApiV1AdmissionsGet(page?: number, limit?: number, statusFilter?: AdmissionStatus | null, classRequested?: string | null, studentName?: string | null, parentName?: string | null, options?: RawAxiosRequestConfig) {
        return AdmissionsApiFp(this.configuration).getAdmissionsApiV1AdmissionsGet(page, limit, statusFilter, classRequested, studentName, parentName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mettre à jour une admission complète.  - **admission_id**: ID de l\'admission à mettre à jour - Tous les champs de l\'admission peuvent être mis à jour  Met automatiquement à jour le champ `updated_at`.
     * @summary Update Admission
     * @param {number} admissionId 
     * @param {AdmissionUpdate} admissionUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdmissionsApi
     */
    public updateAdmissionApiV1AdmissionsAdmissionIdPut(admissionId: number, admissionUpdate: AdmissionUpdate, options?: RawAxiosRequestConfig) {
        return AdmissionsApiFp(this.configuration).updateAdmissionApiV1AdmissionsAdmissionIdPut(admissionId, admissionUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mettre à jour le statut d\'une admission.  - **admission_id**: ID de l\'admission à mettre à jour - **status**: Nouveau statut (ACCEPTED, REJECTED, WAITLIST) - **admin_notes**: Notes de l\'administrateur (optionnel) - **reviewed_by**: Nom de l\'administrateur (optionnel)  Met automatiquement à jour les champs `reviewed_at` et `updated_at`.
     * @summary Update Admission Status
     * @param {number} admissionId 
     * @param {AdmissionStatusUpdate} admissionStatusUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdmissionsApi
     */
    public updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch(admissionId: number, admissionStatusUpdate: AdmissionStatusUpdate, options?: RawAxiosRequestConfig) {
        return AdmissionsApiFp(this.configuration).updateAdmissionStatusApiV1AdmissionsAdmissionIdStatusPatch(admissionId, admissionStatusUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Endpoint de santé pour Docker et monitoring avec test de connexion DB
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Endpoint racine pour vérifier que l\'API fonctionne
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Endpoint de santé pour Docker et monitoring avec test de connexion DB
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthCheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Endpoint racine pour vérifier que l\'API fonctionne
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.rootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Endpoint de santé pour Docker et monitoring avec test de connexion DB
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Endpoint racine pour vérifier que l\'API fonctionne
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Endpoint de santé pour Docker et monitoring avec test de connexion DB
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheckHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Endpoint racine pour vérifier que l\'API fonctionne
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



