/* tslint:disable */
/* eslint-disable */
/**
 * Provisioning Service
 * Service de provisioning automatique des comptes Keycloak
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BatchCreateRequest
 */
export interface BatchCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof BatchCreateRequest
     */
    'source_identity_batch_id': string;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface ProvisioningBatch
 */
export interface ProvisioningBatch {
    /**
     * 
     * @type {string}
     * @memberof ProvisioningBatch
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningBatch
     */
    'source_identity_batch_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningBatch
     */
    'created_by': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningBatch
     */
    'created_at': string;
}
/**
 * 
 * @export
 * @interface ProvisioningItem
 */
export interface ProvisioningItem {
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'provisioning_batch_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'identity_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'domain': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'establishment_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'external_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'firstname': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'lastname': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'email': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'kc_username': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'kc_user_id': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'role_principal_code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'prov_status': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'last_error': string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningItem
     */
    'updated_at': string;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Endpoint de santé de l\'application.  Vérifie : - Connexion à la base de données - État du consommateur RabbitMQ - Connexion à Keycloak
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Endpoint racine avec informations sur le service.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Endpoint de santé de l\'application.  Vérifie : - Connexion à la base de données - État du consommateur RabbitMQ - Connexion à Keycloak
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthCheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Endpoint racine avec informations sur le service.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.rootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Endpoint de santé de l\'application.  Vérifie : - Connexion à la base de données - État du consommateur RabbitMQ - Connexion à Keycloak
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Endpoint racine avec informations sur le service.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Endpoint de santé de l\'application.  Vérifie : - Connexion à la base de données - État du consommateur RabbitMQ - Connexion à Keycloak
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheckHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Endpoint racine avec informations sur le service.
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProvisioningApi - axios parameter creator
 * @export
 */
export const ProvisioningApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Batch
         * @param {BatchCreateRequest} batchCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBatchProvisioningBatchesPost: async (batchCreateRequest: BatchCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchCreateRequest' is not null or undefined
            assertParamExists('createBatchProvisioningBatchesPost', 'batchCreateRequest', batchCreateRequest)
            const localVarPath = `/provisioning/batches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(batchCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Batch
         * @param {BatchCreateRequest} batchCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBatchProvisioningBatchesPost_1: async (batchCreateRequest: BatchCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchCreateRequest' is not null or undefined
            assertParamExists('createBatchProvisioningBatchesPost_1', 'batchCreateRequest', batchCreateRequest)
            const localVarPath = `/provisioning/batches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(batchCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
         * @summary Create Test Item
         * @param {string} batchId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTestItemProvisioningBatchesBatchIdTestItemsPost: async (batchId: string, requestBody: { [key: string]: any; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchId' is not null or undefined
            assertParamExists('createTestItemProvisioningBatchesBatchIdTestItemsPost', 'batchId', batchId)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('createTestItemProvisioningBatchesBatchIdTestItemsPost', 'requestBody', requestBody)
            const localVarPath = `/provisioning/batches/{batch_id}/test-items`
                .replace(`{${"batch_id"}}`, encodeURIComponent(String(batchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
         * @summary Create Test Item
         * @param {string} batchId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTestItemProvisioningBatchesBatchIdTestItemsPost_2: async (batchId: string, requestBody: { [key: string]: any; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchId' is not null or undefined
            assertParamExists('createTestItemProvisioningBatchesBatchIdTestItemsPost_2', 'batchId', batchId)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('createTestItemProvisioningBatchesBatchIdTestItemsPost_2', 'requestBody', requestBody)
            const localVarPath = `/provisioning/batches/{batch_id}/test-items`
                .replace(`{${"batch_id"}}`, encodeURIComponent(String(batchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
         * @summary Generate Username
         * @param {string} firstname 
         * @param {string} lastname 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUsernameProvisioningGenerateUsernamePost: async (firstname: string, lastname: string, email?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'firstname' is not null or undefined
            assertParamExists('generateUsernameProvisioningGenerateUsernamePost', 'firstname', firstname)
            // verify required parameter 'lastname' is not null or undefined
            assertParamExists('generateUsernameProvisioningGenerateUsernamePost', 'lastname', lastname)
            const localVarPath = `/provisioning/generate-username`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (firstname !== undefined) {
                localVarQueryParameter['firstname'] = firstname;
            }

            if (lastname !== undefined) {
                localVarQueryParameter['lastname'] = lastname;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
         * @summary Generate Username
         * @param {string} firstname 
         * @param {string} lastname 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUsernameProvisioningGenerateUsernamePost_3: async (firstname: string, lastname: string, email?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'firstname' is not null or undefined
            assertParamExists('generateUsernameProvisioningGenerateUsernamePost_3', 'firstname', firstname)
            // verify required parameter 'lastname' is not null or undefined
            assertParamExists('generateUsernameProvisioningGenerateUsernamePost_3', 'lastname', lastname)
            const localVarPath = `/provisioning/generate-username`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (firstname !== undefined) {
                localVarQueryParameter['firstname'] = firstname;
            }

            if (lastname !== undefined) {
                localVarQueryParameter['lastname'] = lastname;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Batch Items
         * @param {string} batchId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchItemsProvisioningBatchesBatchIdItemsGet: async (batchId: string, skip?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchId' is not null or undefined
            assertParamExists('listBatchItemsProvisioningBatchesBatchIdItemsGet', 'batchId', batchId)
            const localVarPath = `/provisioning/batches/{batch_id}/items`
                .replace(`{${"batch_id"}}`, encodeURIComponent(String(batchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Batch Items
         * @param {string} batchId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchItemsProvisioningBatchesBatchIdItemsGet_4: async (batchId: string, skip?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchId' is not null or undefined
            assertParamExists('listBatchItemsProvisioningBatchesBatchIdItemsGet_4', 'batchId', batchId)
            const localVarPath = `/provisioning/batches/{batch_id}/items`
                .replace(`{${"batch_id"}}`, encodeURIComponent(String(batchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Batches
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchesProvisioningBatchesGet: async (skip?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/provisioning/batches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Batches
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchesProvisioningBatchesGet_5: async (skip?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/provisioning/batches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Run Batch
         * @param {string} batchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runBatchProvisioningBatchesBatchIdRunPost: async (batchId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchId' is not null or undefined
            assertParamExists('runBatchProvisioningBatchesBatchIdRunPost', 'batchId', batchId)
            const localVarPath = `/provisioning/batches/{batch_id}/run`
                .replace(`{${"batch_id"}}`, encodeURIComponent(String(batchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Run Batch
         * @param {string} batchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runBatchProvisioningBatchesBatchIdRunPost_6: async (batchId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchId' is not null or undefined
            assertParamExists('runBatchProvisioningBatchesBatchIdRunPost_6', 'batchId', batchId)
            const localVarPath = `/provisioning/batches/{batch_id}/run`
                .replace(`{${"batch_id"}}`, encodeURIComponent(String(batchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProvisioningApi - functional programming interface
 * @export
 */
export const ProvisioningApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProvisioningApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Batch
         * @param {BatchCreateRequest} batchCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBatchProvisioningBatchesPost(batchCreateRequest: BatchCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProvisioningBatch>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBatchProvisioningBatchesPost(batchCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.createBatchProvisioningBatchesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create Batch
         * @param {BatchCreateRequest} batchCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBatchProvisioningBatchesPost_1(batchCreateRequest: BatchCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProvisioningBatch>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBatchProvisioningBatchesPost_1(batchCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.createBatchProvisioningBatchesPost_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
         * @summary Create Test Item
         * @param {string} batchId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTestItemProvisioningBatchesBatchIdTestItemsPost(batchId: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTestItemProvisioningBatchesBatchIdTestItemsPost(batchId, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.createTestItemProvisioningBatchesBatchIdTestItemsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
         * @summary Create Test Item
         * @param {string} batchId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTestItemProvisioningBatchesBatchIdTestItemsPost_2(batchId: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTestItemProvisioningBatchesBatchIdTestItemsPost_2(batchId, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.createTestItemProvisioningBatchesBatchIdTestItemsPost_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
         * @summary Generate Username
         * @param {string} firstname 
         * @param {string} lastname 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateUsernameProvisioningGenerateUsernamePost(firstname: string, lastname: string, email?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateUsernameProvisioningGenerateUsernamePost(firstname, lastname, email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.generateUsernameProvisioningGenerateUsernamePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
         * @summary Generate Username
         * @param {string} firstname 
         * @param {string} lastname 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateUsernameProvisioningGenerateUsernamePost_3(firstname: string, lastname: string, email?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateUsernameProvisioningGenerateUsernamePost_3(firstname, lastname, email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.generateUsernameProvisioningGenerateUsernamePost_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Batch Items
         * @param {string} batchId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBatchItemsProvisioningBatchesBatchIdItemsGet(batchId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProvisioningItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBatchItemsProvisioningBatchesBatchIdItemsGet(batchId, skip, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.listBatchItemsProvisioningBatchesBatchIdItemsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Batch Items
         * @param {string} batchId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBatchItemsProvisioningBatchesBatchIdItemsGet_4(batchId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProvisioningItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBatchItemsProvisioningBatchesBatchIdItemsGet_4(batchId, skip, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.listBatchItemsProvisioningBatchesBatchIdItemsGet_4']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Batches
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBatchesProvisioningBatchesGet(skip?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProvisioningBatch>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBatchesProvisioningBatchesGet(skip, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.listBatchesProvisioningBatchesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Batches
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBatchesProvisioningBatchesGet_5(skip?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProvisioningBatch>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBatchesProvisioningBatchesGet_5(skip, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.listBatchesProvisioningBatchesGet_5']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Run Batch
         * @param {string} batchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runBatchProvisioningBatchesBatchIdRunPost(batchId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runBatchProvisioningBatchesBatchIdRunPost(batchId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.runBatchProvisioningBatchesBatchIdRunPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Run Batch
         * @param {string} batchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runBatchProvisioningBatchesBatchIdRunPost_6(batchId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runBatchProvisioningBatchesBatchIdRunPost_6(batchId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProvisioningApi.runBatchProvisioningBatchesBatchIdRunPost_6']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProvisioningApi - factory interface
 * @export
 */
export const ProvisioningApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProvisioningApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Batch
         * @param {BatchCreateRequest} batchCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBatchProvisioningBatchesPost(batchCreateRequest: BatchCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProvisioningBatch> {
            return localVarFp.createBatchProvisioningBatchesPost(batchCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Batch
         * @param {BatchCreateRequest} batchCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBatchProvisioningBatchesPost_1(batchCreateRequest: BatchCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProvisioningBatch> {
            return localVarFp.createBatchProvisioningBatchesPost_1(batchCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
         * @summary Create Test Item
         * @param {string} batchId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTestItemProvisioningBatchesBatchIdTestItemsPost(batchId: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.createTestItemProvisioningBatchesBatchIdTestItemsPost(batchId, requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
         * @summary Create Test Item
         * @param {string} batchId 
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTestItemProvisioningBatchesBatchIdTestItemsPost_2(batchId: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.createTestItemProvisioningBatchesBatchIdTestItemsPost_2(batchId, requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
         * @summary Generate Username
         * @param {string} firstname 
         * @param {string} lastname 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUsernameProvisioningGenerateUsernamePost(firstname: string, lastname: string, email?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.generateUsernameProvisioningGenerateUsernamePost(firstname, lastname, email, options).then((request) => request(axios, basePath));
        },
        /**
         * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
         * @summary Generate Username
         * @param {string} firstname 
         * @param {string} lastname 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUsernameProvisioningGenerateUsernamePost_3(firstname: string, lastname: string, email?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.generateUsernameProvisioningGenerateUsernamePost_3(firstname, lastname, email, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Batch Items
         * @param {string} batchId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchItemsProvisioningBatchesBatchIdItemsGet(batchId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProvisioningItem>> {
            return localVarFp.listBatchItemsProvisioningBatchesBatchIdItemsGet(batchId, skip, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Batch Items
         * @param {string} batchId 
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchItemsProvisioningBatchesBatchIdItemsGet_4(batchId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProvisioningItem>> {
            return localVarFp.listBatchItemsProvisioningBatchesBatchIdItemsGet_4(batchId, skip, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Batches
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchesProvisioningBatchesGet(skip?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProvisioningBatch>> {
            return localVarFp.listBatchesProvisioningBatchesGet(skip, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Batches
         * @param {number} [skip] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBatchesProvisioningBatchesGet_5(skip?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProvisioningBatch>> {
            return localVarFp.listBatchesProvisioningBatchesGet_5(skip, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Run Batch
         * @param {string} batchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runBatchProvisioningBatchesBatchIdRunPost(batchId: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.runBatchProvisioningBatchesBatchIdRunPost(batchId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Run Batch
         * @param {string} batchId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runBatchProvisioningBatchesBatchIdRunPost_6(batchId: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.runBatchProvisioningBatchesBatchIdRunPost_6(batchId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProvisioningApi - object-oriented interface
 * @export
 * @class ProvisioningApi
 * @extends {BaseAPI}
 */
export class ProvisioningApi extends BaseAPI {
    /**
     * 
     * @summary Create Batch
     * @param {BatchCreateRequest} batchCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public createBatchProvisioningBatchesPost(batchCreateRequest: BatchCreateRequest, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).createBatchProvisioningBatchesPost(batchCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Batch
     * @param {BatchCreateRequest} batchCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public createBatchProvisioningBatchesPost_1(batchCreateRequest: BatchCreateRequest, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).createBatchProvisioningBatchesPost_1(batchCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
     * @summary Create Test Item
     * @param {string} batchId 
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public createTestItemProvisioningBatchesBatchIdTestItemsPost(batchId: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).createTestItemProvisioningBatchesBatchIdTestItemsPost(batchId, requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Crée un item de test pour un batch (pour les tests uniquement).  Args:     batch_id: ID du batch     item_data: Données de l\'item avec les clés:         - identity_id: UUID de l\'identité         - firstname: Prénom         - lastname: Nom         - email: Email         - role_principal_code: Rôle principal         - establishment_id: ID de l\'établissement (optionnel)
     * @summary Create Test Item
     * @param {string} batchId 
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public createTestItemProvisioningBatchesBatchIdTestItemsPost_2(batchId: string, requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).createTestItemProvisioningBatchesBatchIdTestItemsPost_2(batchId, requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
     * @summary Generate Username
     * @param {string} firstname 
     * @param {string} lastname 
     * @param {string} [email] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public generateUsernameProvisioningGenerateUsernamePost(firstname: string, lastname: string, email?: string, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).generateUsernameProvisioningGenerateUsernamePost(firstname, lastname, email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Génère un username unique au format firstname.lastname001.  Args:     firstname: Prénom de l\'utilisateur     lastname: Nom de famille de l\'utilisateur     email: Email de l\'utilisateur (optionnel, utilisé comme fallback)  Returns:     dict: Username généré
     * @summary Generate Username
     * @param {string} firstname 
     * @param {string} lastname 
     * @param {string} [email] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public generateUsernameProvisioningGenerateUsernamePost_3(firstname: string, lastname: string, email?: string, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).generateUsernameProvisioningGenerateUsernamePost_3(firstname, lastname, email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Batch Items
     * @param {string} batchId 
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public listBatchItemsProvisioningBatchesBatchIdItemsGet(batchId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).listBatchItemsProvisioningBatchesBatchIdItemsGet(batchId, skip, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Batch Items
     * @param {string} batchId 
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public listBatchItemsProvisioningBatchesBatchIdItemsGet_4(batchId: string, skip?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).listBatchItemsProvisioningBatchesBatchIdItemsGet_4(batchId, skip, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Batches
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public listBatchesProvisioningBatchesGet(skip?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).listBatchesProvisioningBatchesGet(skip, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Batches
     * @param {number} [skip] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public listBatchesProvisioningBatchesGet_5(skip?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).listBatchesProvisioningBatchesGet_5(skip, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Run Batch
     * @param {string} batchId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public runBatchProvisioningBatchesBatchIdRunPost(batchId: string, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).runBatchProvisioningBatchesBatchIdRunPost(batchId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Run Batch
     * @param {string} batchId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProvisioningApi
     */
    public runBatchProvisioningBatchesBatchIdRunPost_6(batchId: string, options?: RawAxiosRequestConfig) {
        return ProvisioningApiFp(this.configuration).runBatchProvisioningBatchesBatchIdRunPost_6(batchId, options).then((request) => request(this.axios, this.basePath));
    }
}



