/* tslint:disable */
/* eslint-disable */
/**
 * Etablissement Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Un établissement unique ou une liste d\'établissements à créer
 * @export
 * @interface Data
 */
export interface Data {
    /**
     * Nom de l\'établissement
     * @type {string}
     * @memberof Data
     */
    'nom': string;
    /**
     * Adresse de l\'établissement
     * @type {string}
     * @memberof Data
     */
    'adresse': string;
    /**
     * Email de contact
     * @type {string}
     * @memberof Data
     */
    'email': string;
    /**
     * Numéro de téléphone
     * @type {string}
     * @memberof Data
     */
    'telephone': string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'ville'?: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'pays'?: string;
    /**
     * 
     * @type {PlanEnum}
     * @memberof Data
     */
    'plan'?: PlanEnum;
    /**
     * 
     * @type {StatusEnum}
     * @memberof Data
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'date_debut'?: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    'date_fin'?: string;
}


/**
 * Schéma pour la mise à jour des coordonnées uniquement
 * @export
 * @interface EtablissementCoordinatesUpdate
 */
export interface EtablissementCoordinatesUpdate {
    /**
     * 
     * @type {string}
     * @memberof EtablissementCoordinatesUpdate
     */
    'nom'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCoordinatesUpdate
     */
    'adresse'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCoordinatesUpdate
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCoordinatesUpdate
     */
    'telephone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCoordinatesUpdate
     */
    'ville'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCoordinatesUpdate
     */
    'pays'?: string | null;
}
/**
 * 
 * @export
 * @interface EtablissementCreate
 */
export interface EtablissementCreate {
    /**
     * Nom de l\'établissement
     * @type {string}
     * @memberof EtablissementCreate
     */
    'nom': string;
    /**
     * Adresse de l\'établissement
     * @type {string}
     * @memberof EtablissementCreate
     */
    'adresse': string;
    /**
     * Email de contact
     * @type {string}
     * @memberof EtablissementCreate
     */
    'email': string;
    /**
     * Numéro de téléphone
     * @type {string}
     * @memberof EtablissementCreate
     */
    'telephone': string;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCreate
     */
    'ville'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCreate
     */
    'pays'?: string | null;
    /**
     * 
     * @type {PlanEnum}
     * @memberof EtablissementCreate
     */
    'plan'?: PlanEnum;
    /**
     * 
     * @type {StatusEnum}
     * @memberof EtablissementCreate
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCreate
     */
    'date_debut'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementCreate
     */
    'date_fin'?: string | null;
}


/**
 * Schéma flexible pour accepter soit un établissement unique, soit une liste d\'établissements. Permet de créer un ou plusieurs établissements avec le même endpoint.
 * @export
 * @interface EtablissementCreateFlexible
 */
export interface EtablissementCreateFlexible {
    /**
     * 
     * @type {Data}
     * @memberof EtablissementCreateFlexible
     */
    'data': Data;
}
/**
 * 
 * @export
 * @interface EtablissementOut
 */
export interface EtablissementOut {
    /**
     * Nom de l\'établissement
     * @type {string}
     * @memberof EtablissementOut
     */
    'nom': string;
    /**
     * Adresse de l\'établissement
     * @type {string}
     * @memberof EtablissementOut
     */
    'adresse': string;
    /**
     * Email de contact
     * @type {string}
     * @memberof EtablissementOut
     */
    'email': string;
    /**
     * Numéro de téléphone
     * @type {string}
     * @memberof EtablissementOut
     */
    'telephone': string;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'ville'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'pays'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'id': string;
    /**
     * 
     * @type {PlanEnum}
     * @memberof EtablissementOut
     */
    'plan': PlanEnum;
    /**
     * 
     * @type {StatusEnum}
     * @memberof EtablissementOut
     */
    'status': StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'date_debut': string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'date_fin': string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'subscription_start'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'subscription_end'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'etablissement_group': string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'etablissement_id': string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'updated_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementOut
     */
    'deleted_at'?: string | null;
}


/**
 * 
 * @export
 * @interface EtablissementUpdate
 */
export interface EtablissementUpdate {
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'nom'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'adresse'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'telephone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'ville'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'pays'?: string | null;
    /**
     * 
     * @type {PlanEnum}
     * @memberof EtablissementUpdate
     */
    'plan'?: PlanEnum | null;
    /**
     * 
     * @type {StatusEnum}
     * @memberof EtablissementUpdate
     */
    'status'?: StatusEnum | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'date_debut'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EtablissementUpdate
     */
    'date_fin'?: string | null;
}


/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const PlanEnum = {
    Basic: 'BASIC',
    Pro: 'PRO',
    Entreprise: 'ENTREPRISE'
} as const;

export type PlanEnum = typeof PlanEnum[keyof typeof PlanEnum];


/**
 * 
 * @export
 * @interface ResponseCreateEstablishmentApiEtablissementsPost
 */
export interface ResponseCreateEstablishmentApiEtablissementsPost {
    /**
     * Nom de l\'établissement
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'nom': string;
    /**
     * Adresse de l\'établissement
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'adresse': string;
    /**
     * Email de contact
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'email': string;
    /**
     * Numéro de téléphone
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'telephone': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'ville'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'pays'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'id': string;
    /**
     * 
     * @type {PlanEnum}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'plan': PlanEnum;
    /**
     * 
     * @type {StatusEnum}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'status': StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'date_debut': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'date_fin': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'subscription_start'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'subscription_end'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'etablissement_group': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'etablissement_id': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'updated_at': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateEstablishmentApiEtablissementsPost
     */
    'deleted_at'?: string;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const StatusEnum = {
    Trial: 'TRIAL',
    Active: 'ACTIVE',
    Suspended: 'SUSPENDED',
    Closed: 'CLOSED'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Endpoint racine de l\'application.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Endpoint racine de l\'application.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.rootGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Endpoint racine de l\'application.
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Endpoint racine de l\'application.
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EstablishmentsApi - axios parameter creator
 * @export
 */
export const EstablishmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Crée un ou plusieurs établissements  Accepte soit un établissement unique, soit une liste d\'établissements. En cas d\'erreur sur un seul établissement, tous sont annulés (rollback complet).  Requiert le rôle ROLE_ADMIN.
         * @summary Create Establishment
         * @param {EtablissementCreateFlexible} etablissementCreateFlexible 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEstablishmentApiEtablissementsPost: async (etablissementCreateFlexible: EtablissementCreateFlexible, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'etablissementCreateFlexible' is not null or undefined
            assertParamExists('createEstablishmentApiEtablissementsPost', 'etablissementCreateFlexible', etablissementCreateFlexible)
            const localVarPath = `/api/etablissements/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(etablissementCreateFlexible, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Récupère un établissement par son ID  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut accéder qu\'à son propre établissement.
         * @summary Get Establishment
         * @param {string} establishmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEstablishmentApiEtablissementsEstablishmentIdGet: async (establishmentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'establishmentId' is not null or undefined
            assertParamExists('getEstablishmentApiEtablissementsEstablishmentIdGet', 'establishmentId', establishmentId)
            const localVarPath = `/api/etablissements/{establishment_id}`
                .replace(`{${"establishment_id"}}`, encodeURIComponent(String(establishmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Liste tous les établissements avec pagination et filtres  Requiert le rôle ROLE_ADMIN.
         * @summary List Establishments
         * @param {StatusEnum} [status] Filtrer par statut
         * @param {number} [limit] Nombre maximum d\&#39;éléments
         * @param {number} [offset] Offset pour la pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEstablishmentsApiEtablissementsGet: async (status?: StatusEnum, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/etablissements/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Liste publique des etablissements actifs  Aucune authentification requise - accessible publiquement. Retourne seulement les etablissements avec le statut ACTIVE.
         * @summary List Public Establishments
         * @param {number} [limit] Nombre maximum d\&#39;elements
         * @param {number} [offset] Offset pour la pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPublicEstablishmentsApiEtablissementsPublicGet: async (limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/etablissements/public/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Met à jour les informations d\'un établissement
         * @summary Update Establishment
         * @param {string} establishmentId 
         * @param {EtablissementUpdate} etablissementUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEstablishmentApiEtablissementsEstablishmentIdPatch: async (establishmentId: string, etablissementUpdate: EtablissementUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'establishmentId' is not null or undefined
            assertParamExists('updateEstablishmentApiEtablissementsEstablishmentIdPatch', 'establishmentId', establishmentId)
            // verify required parameter 'etablissementUpdate' is not null or undefined
            assertParamExists('updateEstablishmentApiEtablissementsEstablishmentIdPatch', 'etablissementUpdate', etablissementUpdate)
            const localVarPath = `/api/etablissements/{establishment_id}`
                .replace(`{${"establishment_id"}}`, encodeURIComponent(String(establishmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(etablissementUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Met à jour les coordonnées d\'un établissement  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut modifier que son propre établissement.
         * @summary Update Establishment Coordinates
         * @param {string} establishmentId 
         * @param {EtablissementCoordinatesUpdate} etablissementCoordinatesUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch: async (establishmentId: string, etablissementCoordinatesUpdate: EtablissementCoordinatesUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'establishmentId' is not null or undefined
            assertParamExists('updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch', 'establishmentId', establishmentId)
            // verify required parameter 'etablissementCoordinatesUpdate' is not null or undefined
            assertParamExists('updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch', 'etablissementCoordinatesUpdate', etablissementCoordinatesUpdate)
            const localVarPath = `/api/etablissements/{establishment_id}/coordinates`
                .replace(`{${"establishment_id"}}`, encodeURIComponent(String(establishmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(etablissementCoordinatesUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Met à jour le statut d\'un établissement  Requiert le rôle ROLE_ADMIN.
         * @summary Update Establishment Status
         * @param {string} establishmentId 
         * @param {StatusEnum} status 
         * @param {string} [motif] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch: async (establishmentId: string, status: StatusEnum, motif?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'establishmentId' is not null or undefined
            assertParamExists('updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch', 'establishmentId', establishmentId)
            // verify required parameter 'status' is not null or undefined
            assertParamExists('updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch', 'status', status)
            const localVarPath = `/api/etablissements/{establishment_id}/status`
                .replace(`{${"establishment_id"}}`, encodeURIComponent(String(establishmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (motif !== undefined) {
                localVarQueryParameter['motif'] = motif;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EstablishmentsApi - functional programming interface
 * @export
 */
export const EstablishmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EstablishmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Crée un ou plusieurs établissements  Accepte soit un établissement unique, soit une liste d\'établissements. En cas d\'erreur sur un seul établissement, tous sont annulés (rollback complet).  Requiert le rôle ROLE_ADMIN.
         * @summary Create Establishment
         * @param {EtablissementCreateFlexible} etablissementCreateFlexible 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createEstablishmentApiEtablissementsPost(etablissementCreateFlexible: EtablissementCreateFlexible, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseCreateEstablishmentApiEtablissementsPost>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createEstablishmentApiEtablissementsPost(etablissementCreateFlexible, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentsApi.createEstablishmentApiEtablissementsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Récupère un établissement par son ID  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut accéder qu\'à son propre établissement.
         * @summary Get Establishment
         * @param {string} establishmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEstablishmentApiEtablissementsEstablishmentIdGet(establishmentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EtablissementOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEstablishmentApiEtablissementsEstablishmentIdGet(establishmentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentsApi.getEstablishmentApiEtablissementsEstablishmentIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Liste tous les établissements avec pagination et filtres  Requiert le rôle ROLE_ADMIN.
         * @summary List Establishments
         * @param {StatusEnum} [status] Filtrer par statut
         * @param {number} [limit] Nombre maximum d\&#39;éléments
         * @param {number} [offset] Offset pour la pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEstablishmentsApiEtablissementsGet(status?: StatusEnum, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EtablissementOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEstablishmentsApiEtablissementsGet(status, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentsApi.listEstablishmentsApiEtablissementsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Liste publique des etablissements actifs  Aucune authentification requise - accessible publiquement. Retourne seulement les etablissements avec le statut ACTIVE.
         * @summary List Public Establishments
         * @param {number} [limit] Nombre maximum d\&#39;elements
         * @param {number} [offset] Offset pour la pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPublicEstablishmentsApiEtablissementsPublicGet(limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EtablissementOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPublicEstablishmentsApiEtablissementsPublicGet(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentsApi.listPublicEstablishmentsApiEtablissementsPublicGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Met à jour les informations d\'un établissement
         * @summary Update Establishment
         * @param {string} establishmentId 
         * @param {EtablissementUpdate} etablissementUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEstablishmentApiEtablissementsEstablishmentIdPatch(establishmentId: string, etablissementUpdate: EtablissementUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EtablissementOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEstablishmentApiEtablissementsEstablishmentIdPatch(establishmentId, etablissementUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentsApi.updateEstablishmentApiEtablissementsEstablishmentIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Met à jour les coordonnées d\'un établissement  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut modifier que son propre établissement.
         * @summary Update Establishment Coordinates
         * @param {string} establishmentId 
         * @param {EtablissementCoordinatesUpdate} etablissementCoordinatesUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch(establishmentId: string, etablissementCoordinatesUpdate: EtablissementCoordinatesUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EtablissementOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch(establishmentId, etablissementCoordinatesUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentsApi.updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Met à jour le statut d\'un établissement  Requiert le rôle ROLE_ADMIN.
         * @summary Update Establishment Status
         * @param {string} establishmentId 
         * @param {StatusEnum} status 
         * @param {string} [motif] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch(establishmentId: string, status: StatusEnum, motif?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EtablissementOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch(establishmentId, status, motif, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EstablishmentsApi.updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EstablishmentsApi - factory interface
 * @export
 */
export const EstablishmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EstablishmentsApiFp(configuration)
    return {
        /**
         * Crée un ou plusieurs établissements  Accepte soit un établissement unique, soit une liste d\'établissements. En cas d\'erreur sur un seul établissement, tous sont annulés (rollback complet).  Requiert le rôle ROLE_ADMIN.
         * @summary Create Establishment
         * @param {EtablissementCreateFlexible} etablissementCreateFlexible 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEstablishmentApiEtablissementsPost(etablissementCreateFlexible: EtablissementCreateFlexible, options?: RawAxiosRequestConfig): AxiosPromise<ResponseCreateEstablishmentApiEtablissementsPost> {
            return localVarFp.createEstablishmentApiEtablissementsPost(etablissementCreateFlexible, options).then((request) => request(axios, basePath));
        },
        /**
         * Récupère un établissement par son ID  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut accéder qu\'à son propre établissement.
         * @summary Get Establishment
         * @param {string} establishmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEstablishmentApiEtablissementsEstablishmentIdGet(establishmentId: string, options?: RawAxiosRequestConfig): AxiosPromise<EtablissementOut> {
            return localVarFp.getEstablishmentApiEtablissementsEstablishmentIdGet(establishmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Liste tous les établissements avec pagination et filtres  Requiert le rôle ROLE_ADMIN.
         * @summary List Establishments
         * @param {StatusEnum} [status] Filtrer par statut
         * @param {number} [limit] Nombre maximum d\&#39;éléments
         * @param {number} [offset] Offset pour la pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEstablishmentsApiEtablissementsGet(status?: StatusEnum, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<EtablissementOut>> {
            return localVarFp.listEstablishmentsApiEtablissementsGet(status, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Liste publique des etablissements actifs  Aucune authentification requise - accessible publiquement. Retourne seulement les etablissements avec le statut ACTIVE.
         * @summary List Public Establishments
         * @param {number} [limit] Nombre maximum d\&#39;elements
         * @param {number} [offset] Offset pour la pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPublicEstablishmentsApiEtablissementsPublicGet(limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<EtablissementOut>> {
            return localVarFp.listPublicEstablishmentsApiEtablissementsPublicGet(limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Met à jour les informations d\'un établissement
         * @summary Update Establishment
         * @param {string} establishmentId 
         * @param {EtablissementUpdate} etablissementUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEstablishmentApiEtablissementsEstablishmentIdPatch(establishmentId: string, etablissementUpdate: EtablissementUpdate, options?: RawAxiosRequestConfig): AxiosPromise<EtablissementOut> {
            return localVarFp.updateEstablishmentApiEtablissementsEstablishmentIdPatch(establishmentId, etablissementUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * Met à jour les coordonnées d\'un établissement  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut modifier que son propre établissement.
         * @summary Update Establishment Coordinates
         * @param {string} establishmentId 
         * @param {EtablissementCoordinatesUpdate} etablissementCoordinatesUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch(establishmentId: string, etablissementCoordinatesUpdate: EtablissementCoordinatesUpdate, options?: RawAxiosRequestConfig): AxiosPromise<EtablissementOut> {
            return localVarFp.updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch(establishmentId, etablissementCoordinatesUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * Met à jour le statut d\'un établissement  Requiert le rôle ROLE_ADMIN.
         * @summary Update Establishment Status
         * @param {string} establishmentId 
         * @param {StatusEnum} status 
         * @param {string} [motif] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch(establishmentId: string, status: StatusEnum, motif?: string, options?: RawAxiosRequestConfig): AxiosPromise<EtablissementOut> {
            return localVarFp.updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch(establishmentId, status, motif, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EstablishmentsApi - object-oriented interface
 * @export
 * @class EstablishmentsApi
 * @extends {BaseAPI}
 */
export class EstablishmentsApi extends BaseAPI {
    /**
     * Crée un ou plusieurs établissements  Accepte soit un établissement unique, soit une liste d\'établissements. En cas d\'erreur sur un seul établissement, tous sont annulés (rollback complet).  Requiert le rôle ROLE_ADMIN.
     * @summary Create Establishment
     * @param {EtablissementCreateFlexible} etablissementCreateFlexible 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentsApi
     */
    public createEstablishmentApiEtablissementsPost(etablissementCreateFlexible: EtablissementCreateFlexible, options?: RawAxiosRequestConfig) {
        return EstablishmentsApiFp(this.configuration).createEstablishmentApiEtablissementsPost(etablissementCreateFlexible, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Récupère un établissement par son ID  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut accéder qu\'à son propre établissement.
     * @summary Get Establishment
     * @param {string} establishmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentsApi
     */
    public getEstablishmentApiEtablissementsEstablishmentIdGet(establishmentId: string, options?: RawAxiosRequestConfig) {
        return EstablishmentsApiFp(this.configuration).getEstablishmentApiEtablissementsEstablishmentIdGet(establishmentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Liste tous les établissements avec pagination et filtres  Requiert le rôle ROLE_ADMIN.
     * @summary List Establishments
     * @param {StatusEnum} [status] Filtrer par statut
     * @param {number} [limit] Nombre maximum d\&#39;éléments
     * @param {number} [offset] Offset pour la pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentsApi
     */
    public listEstablishmentsApiEtablissementsGet(status?: StatusEnum, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return EstablishmentsApiFp(this.configuration).listEstablishmentsApiEtablissementsGet(status, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Liste publique des etablissements actifs  Aucune authentification requise - accessible publiquement. Retourne seulement les etablissements avec le statut ACTIVE.
     * @summary List Public Establishments
     * @param {number} [limit] Nombre maximum d\&#39;elements
     * @param {number} [offset] Offset pour la pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentsApi
     */
    public listPublicEstablishmentsApiEtablissementsPublicGet(limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return EstablishmentsApiFp(this.configuration).listPublicEstablishmentsApiEtablissementsPublicGet(limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Met à jour les informations d\'un établissement
     * @summary Update Establishment
     * @param {string} establishmentId 
     * @param {EtablissementUpdate} etablissementUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentsApi
     */
    public updateEstablishmentApiEtablissementsEstablishmentIdPatch(establishmentId: string, etablissementUpdate: EtablissementUpdate, options?: RawAxiosRequestConfig) {
        return EstablishmentsApiFp(this.configuration).updateEstablishmentApiEtablissementsEstablishmentIdPatch(establishmentId, etablissementUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Met à jour les coordonnées d\'un établissement  Requiert le rôle ROLE_ADMIN ou ROLE_DIRECTION. ROLE_DIRECTION ne peut modifier que son propre établissement.
     * @summary Update Establishment Coordinates
     * @param {string} establishmentId 
     * @param {EtablissementCoordinatesUpdate} etablissementCoordinatesUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentsApi
     */
    public updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch(establishmentId: string, etablissementCoordinatesUpdate: EtablissementCoordinatesUpdate, options?: RawAxiosRequestConfig) {
        return EstablishmentsApiFp(this.configuration).updateEstablishmentCoordinatesApiEtablissementsEstablishmentIdCoordinatesPatch(establishmentId, etablissementCoordinatesUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Met à jour le statut d\'un établissement  Requiert le rôle ROLE_ADMIN.
     * @summary Update Establishment Status
     * @param {string} establishmentId 
     * @param {StatusEnum} status 
     * @param {string} [motif] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EstablishmentsApi
     */
    public updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch(establishmentId: string, status: StatusEnum, motif?: string, options?: RawAxiosRequestConfig) {
        return EstablishmentsApiFp(this.configuration).updateEstablishmentStatusApiEtablissementsEstablishmentIdStatusPatch(establishmentId, status, motif, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Vérifie la santé du service (connexion DB uniquement)
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/health/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Vérifie la santé du service (connexion DB uniquement)
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiHealthGet_1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/health/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * Vérifie la santé du service (connexion DB uniquement)
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckApiHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckApiHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheckApiHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Vérifie la santé du service (connexion DB uniquement)
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckApiHealthGet_1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckApiHealthGet_1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheckApiHealthGet_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * Vérifie la santé du service (connexion DB uniquement)
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckApiHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Vérifie la santé du service (connexion DB uniquement)
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiHealthGet_1(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckApiHealthGet_1(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * Vérifie la santé du service (connexion DB uniquement)
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthCheckApiHealthGet(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheckApiHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Vérifie la santé du service (connexion DB uniquement)
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthCheckApiHealthGet_1(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheckApiHealthGet_1(options).then((request) => request(this.axios, this.basePath));
    }
}



